# Generated by Django 4.2.7 on 2026-09-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_microsoft', '0002_microsoftrepairjob_scope_team_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftrepairjob',
            name='target_type',
            field=models.CharField(choices=[('users', 'Users'), ('courses', 'Courses'), ('unlicensed_users', 'Unlicensed users'), ('scope_team_owners', 'Scope team owners'), ('password_reset', 'Password reset')], max_length=32),
        ),
    ]
