# Generated by Django 4.2.7 on 2026-06-29 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_grading_reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthlyreportbatch",
            options={"ordering": ["-created_at"]},
        ),
    ]
