# Generated by Django 4.2.7 on 2023-11-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.FileField(upload_to="attachments")),
                ("table_name", models.CharField()),
                ("foreign_key", models.BigIntegerField()),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
    ]
