# Generated by Django 4.2.7 on 2023-12-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="is_image",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attachment",
            name="name",
            field=models.CharField(default="name", max_length=5120),
            preserve_default=False,
        ),
    ]
