# Generated by Django 4.2.7 on 2023-12-05 11:50

from django.db import migrations, models

import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0002_attachment_is_image_attachment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="data",
            field=models.FileField(
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to="attachments",
            ),
        ),
    ]
