# Generated by Django 4.2.7 on 2023-12-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0003_alter_attachment_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="reference_key",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
