# Generated by Django 4.2.7 on 2023-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0004_attachment_reference_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="file_type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
