# Generated by Django 4.2.7 on 2023-12-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0005_attachment_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="foreign_key",
            field=models.BigIntegerField(null=True),
        ),
    ]
