# Generated by Django 4.2.7 on 2024-02-06 03:26

from django.db import migrations, models

import app_attachment.models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0006_alter_attachment_foreign_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="data",
            field=models.FileField(
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to=app_attachment.models.get_tenant_specific_upload_folder_for_attachment,
            ),
        ),
    ]
