# Generated by Django 4.2.7 on 2024-02-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0007_alter_attachment_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="reference_key",
            field=models.CharField(db_index=True, max_length=2000, null=True),
        ),
    ]
