# Generated by Django 4.2.7 on 2025-02-22 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0008_alter_attachment_reference_key"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attachment",
        ),
    ]
