# Generated by Django 4.2.7 on 2025-02-22 08:42

from django.db import migrations, models
import drf_chunked_upload.models
import schedjuice_backend.storages
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_attachment", "0009_delete_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        null=True,
                        storage=schedjuice_backend.storages.PrivateMediaStorage(),
                        upload_to=drf_chunked_upload.models.generate_filename,
                    ),
                ),
                ("offset", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Incomplete"), (2, "Complete")], default=1
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("filename", models.CharField(max_length=5120)),
                ("is_image", models.BooleanField()),
                ("file_type", models.CharField(max_length=100, null=True)),
                ("table_name", models.CharField()),
                ("foreign_key", models.BigIntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
