# Generated by Django 4.2.7 on 2025-02-22 09:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0011_attachment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="user",
        ),
    ]
