# Generated by Django 4.2.7 on 2025-02-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0012_remove_attachment_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="file",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="offset",
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="status",
        ),
        migrations.AddField(
            model_name="attachment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
