# Generated by Django 4.2.7 on 2025-03-02 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0013_alter_attachment_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attachment",
        ),
    ]
