# Generated by Django 4.2.7 on 2025-03-02 16:18

import app_attachment.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_attachment", "0014_delete_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=5120)),
                ("is_image", models.BooleanField()),
                (
                    "data",
                    models.FileField(
                        null=True,
                        upload_to=app_attachment.models.get_tenant_specific_upload_folder_for_attachment,
                    ),
                ),
                ("file_type", models.CharField(max_length=100, null=True)),
                ("table_name", models.CharField()),
                ("foreign_key", models.BigIntegerField(null=True)),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
    ]
