# Generated by Django 4.2.7 on 2025-04-30 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0015_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="foreign_key",
        ),
    ]
