# Generated by Django 4.2.7 on 2025-04-30 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_announcement", "0003_news"),
        ("app_attachment", "0016_remove_attachment_foreign_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="news",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="app_announcement.news",
            ),
        ),
    ]
