# Generated by Django 4.2.7 on 2025-05-02 14:30

import app_attachment.models
from django.db import migrations, models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0017_attachment_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="public_data",
            field=models.FileField(
                null=True,
                storage=schedjuice_backend.storages.PublicMediaStorage(),
                upload_to=app_attachment.models.get_tenant_specific_upload_folder_for_attachment,
            ),
        ),
    ]
