# Generated by Django 4.2.7 on 2025-05-17 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_course",
            "0032_rename_available_date_assignment_available_datetime_and_more",
        ),
        ("app_attachment", "0018_attachment_public_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="assignment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="app_course.assignment",
            ),
        ),
    ]
