# Generated by Django 4.2.7 on 2025-08-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0020_attachment_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="access_count",
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="attachment",
            name="foreign_key",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attachment",
            name="last_accessed",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="size",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
