# Generated by Django 4.2.7 on 2025-10-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_attachment",
            "0021_attachment_access_count_attachment_foreign_key_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="data",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
