# Generated by Django 4.2.7 on 2025-11-23 06:04

from django.db import migrations, models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0022_alter_attachment_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="data",
            field=models.FileField(
                null=True,
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to="",
            ),
        ),
    ]
