# Generated by Django 4.2.7 on 2026-06-29 09:04

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_ai", "0002_airequestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="airequestlog",
            name="likely_causes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name="airequestlog",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["likely_causes"],
                name="ix_ai_req_likely_causes",
                opclasses=["jsonb_path_ops"],
            ),
        ),
    ]
