# Generated by Django 4.2.7 on 2026-06-29 12:00

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_ai", "0003_airequestlog_likely_causes"),
    ]

    operations = [
        migrations.AddField(
            model_name="airequestlog",
            name="capability_gap_domain",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="airequestlog",
            name="capability_gap_intent",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="airequestlog",
            name="capability_gap_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="airequestlog",
            name="capability_gap_suggested_surface",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="airequestlog",
            name="capability_gaps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="airequestlog",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("success", "success"),
                    ("tool_limit_exceeded", "tool_limit_exceeded"),
                    ("capability_gap", "capability_gap"),
                    ("error", "error"),
                    ("blocked", "blocked"),
                    ("rate_limited", "rate_limited"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="airequestlog",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["capability_gaps"],
                name="ix_ai_req_capability_gaps",
                opclasses=["jsonb_path_ops"],
            ),
        ),
    ]
