# Generated by Django 4.2.7 on 2026-07-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_ai", "0004_airequestlog_capability_gap"),
    ]

    operations = [
        migrations.AddField(
            model_name="airequestlog",
            name="thinking_steps",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
