# Generated by Django 4.2.7 on 2026-08-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0092_googlecalendarpushchannel"),
        ("app_ai", "0008_ai_cache_write_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="OcrExtractionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("image_upload", "image_upload"),
                            (
                                "microsoft_payment_assignment",
                                "microsoft_payment_assignment",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        blank=True,
                        choices=[("preview", "preview"), ("async", "async")],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "success"),
                            ("partial", "partial"),
                            ("error", "error"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "extracted_transaction_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "extracted_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "extracted_bank",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("user_payment_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user_payment_schema",
                    models.CharField(blank=True, default="", max_length=63),
                ),
                (
                    "correctness",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("correct", "correct"),
                            ("corrected", "corrected"),
                            ("failed_extraction", "failed_extraction"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "ocr_endpoint",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_extraction_events",
                        to="app_organization.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="ix_ocr_evt_tenant_created",
                    ),
                    models.Index(
                        fields=["source", "created_at"],
                        name="ix_ocr_evt_source_created",
                    ),
                    models.Index(
                        fields=["correctness", "created_at"],
                        name="ix_ocr_evt_correct_created",
                    ),
                ],
            },
        ),
    ]
