# Generated by Django 4.2.7 on 2026-08-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_ai", "0009_ocr_analytics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airequestlog",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("success", "success"),
                    ("tool_limit_exceeded", "tool_limit_exceeded"),
                    ("capability_gap", "capability_gap"),
                    ("error", "error"),
                    ("blocked", "blocked"),
                    ("rate_limited", "rate_limited"),
                    ("user_quota_exceeded", "user_quota_exceeded"),
                ],
                max_length=32,
            ),
        ),
    ]
