# Generated by Django 4.2.7 on 2026-06-25 04:36

import app_hr.models
from django.db import migrations, models
import django.db.models.deletion
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0098_campus_geofence_fields"),
        ("app_hr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingcheckin",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="building_checkins",
                to="app_course.campus",
            ),
        ),
        migrations.AddField(
            model_name="buildingcheckin",
            name="checkin_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to=app_hr.models.get_tenant_specific_upload_folder_for_campus_checkin_image,
            ),
        ),
        migrations.AddField(
            model_name="buildingcheckin",
            name="checkin_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="buildingcheckin",
            name="checkin_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="buildingcheckin",
            name="checkin_verification_method",
            field=models.CharField(
                blank=True,
                choices=[("geo", "geo"), ("selfie", "selfie")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="buildingcheckin",
            name="checkout_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to=app_hr.models.get_tenant_specific_upload_folder_for_campus_checkin_image,
            ),
        ),
        migrations.AddField(
            model_name="buildingcheckin",
            name="checkout_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="buildingcheckin",
            name="checkout_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="buildingcheckin",
            name="checkout_verification_method",
            field=models.CharField(
                blank=True,
                choices=[("geo", "geo"), ("selfie", "selfie")],
                max_length=16,
                null=True,
            ),
        ),
    ]
