from __future__ import annotations

CAPABILITY_GAP_MISSING_TOOL = "missing_tool"
CAPABILITY_GAP_DATA_NOT_EXPOSED = "data_not_exposed"
CAPABILITY_GAP_ACCESS_POLICY = "access_policy"
CAPABILITY_GAP_FEATURE_UNAVAILABLE = "feature_unavailable"
CAPABILITY_GAP_UNKNOWN = "unknown"

VALID_CAPABILITY_GAPS = frozenset(
    {
        CAPABILITY_GAP_MISSING_TOOL,
        CAPABILITY_GAP_DATA_NOT_EXPOSED,
        CAPABILITY_GAP_ACCESS_POLICY,
        CAPABILITY_GAP_FEATURE_UNAVAILABLE,
        CAPABILITY_GAP_UNKNOWN,
    }
)

JUDGE_PROMPT_MAX_CHARS = 500
JUDGE_RESPONSE_MAX_CHARS = 800
JUDGE_HISTORY_USER_MAX_CHARS = 400
JUDGE_HISTORY_MODEL_MAX_CHARS = 600
JUDGE_TRUNCATION_SUFFIX = "… [truncated]"
