# Generated by Django 4.2.7 on 2026-06-17 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_rbac", "0007_course_assign_self_events"),
        ("app_rbac", "0007_unpaid_permissions"),
    ]

    operations = []
