# Generated by Django 4.2.7 on 2026-08-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rbac', '0018_consultation_permissions'),
    ]

    operations = [
    ]
