# Generated by Django 4.2.7 on 2025-05-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_announcement", "0003_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="preview_text",
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
