# Generated by Django 4.2.7 on 2025-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_announcement", "0004_news_preview_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="preview_text",
            field=models.TextField(max_length=2048, null=True),
        ),
    ]
