# Generated by Django 4.2.7 on 2025-05-02 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_announcement", "0005_alter_news_preview_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="preview_text",
        ),
    ]
