# Generated by Django 4.2.7 on 2025-08-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_announcement", "0006_remove_news_preview_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="html_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="json_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
