# Generated by Django 4.2.7 on 2025-08-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_announcement", "0007_announcement_html_data_announcement_json_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
