# Generated by Django 4.2.7 on 2025-10-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_announcement", "0008_alter_announcement_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"ordering": ["-is_pinned", "-created_at"]},
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
