# Generated by Django 4.2.7

from django.db import migrations, models


def default_course_filters():
    return {"month_type": "ALL"}


class Migration(migrations.Migration):
    dependencies = [
        ("app_announcement", "0010_comment_reaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="send_to_microsoft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="announcement",
            name="course_filters",
            field=models.JSONField(blank=True, default=default_course_filters, null=True),
        ),
    ]
