# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion
import app_announcement.models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_announcement", "0011_announcement_send_to_microsoft_course_filters"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=5120)),
                (
                    "file",
                    models.FileField(
                        storage=schedjuice_backend.storages.PublicMediaStorage(),
                        upload_to=app_announcement.models.get_announcement_attachment_upload_path,
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="app_announcement.announcement",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
