# Generated by Django 4.2.7 on 2026-02-18 01:23

import app_announcement.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_announcement", "0012_announcementattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="course_filters",
            field=models.JSONField(
                blank=True,
                default=app_announcement.models.default_course_filters,
                null=True,
            ),
        ),
    ]
