# Generated by Django 4.2.7 on 2026-07-13 11:54

from django.db import migrations, models


def backfill_teams_status(apps, schema_editor):
    Announcement = apps.get_model("app_announcement", "Announcement")
    Course = apps.get_model("app_course", "Course")

    course_ids_with_team = set(
        Course.objects.exclude(microsoft_group_id__isnull=True)
        .exclude(microsoft_group_id="")
        .values_list("id", flat=True)
    )

    Announcement.objects.filter(
        microsoft_teams_message_id__isnull=False,
    ).exclude(microsoft_teams_message_id="").update(
        microsoft_teams_status="sent",
        microsoft_teams_error=None,
    )

    eligible = Announcement.objects.filter(
        send_to_microsoft=True,
        course_id__isnull=False,
        course_id__in=course_ids_with_team,
    ).filter(
        models.Q(microsoft_teams_message_id__isnull=True)
        | models.Q(microsoft_teams_message_id="")
    )
    eligible.update(
        microsoft_teams_status="failed",
        microsoft_teams_error="Not sent to Teams yet",
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("app_announcement", "0016_announcement_teams_message_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="microsoft_channel_id",
            field=models.CharField(
                blank=True,
                help_text="Per-post Teams channel override; falls back to course default.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="microsoft_teams_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="microsoft_teams_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                help_text="Teams delivery status when send_to_microsoft is true.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="microsoft_teams_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_teams_status, noop_reverse),
    ]
