# Generated by Django 4.2.7 on 2026-07-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_announcement", "0017_announcement_teams_status_and_channel_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="microsoft_teams_message_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="All Teams message ids when a post is split across multiple messages.",
                null=True,
            ),
        ),
    ]
