# Generated by Django 4.2.7 on 2026-07-30 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_announcement", "0018_announcement_teams_message_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="microsoft_teams_posted_as",
            field=models.CharField(
                blank=True,
                choices=[("user", "User"), ("service_account", "Service account")],
                help_text="Which identity posted to Teams (user vs org service account).",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="microsoft_teams_posted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Schedjuice user whose Microsoft OAuth posted to Teams, when posted_as=user.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams_posted_announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
