# Generated by Django 4.2.7 on 2026-08-07 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_course", "0106_usercourse_substitute_auto_remove_on"),
        ("app_announcement", "0019_microsoft_delegated_oauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcementattachment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_course.course",
            ),
        ),
        migrations.AddField(
            model_name="announcementattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="announcementattachment",
            name="announcement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="app_announcement.announcement",
            ),
        ),
        migrations.AddIndex(
            model_name="announcementattachment",
            index=models.Index(
                fields=["course", "uploaded_by", "announcement"],
                name="app_announc_course__22163c_idx",
            ),
        ),
    ]
