# Generated by Django 4.2.7 on 2024-08-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tools", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useremail",
            old_name="body",
            new_name="json_body",
        ),
        migrations.AddField(
            model_name="useremail",
            name="html_body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
