# Generated by Django 4.2.7 on 2024-08-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tools", "0002_rename_body_useremail_json_body_useremail_html_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="valid_variables",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
