# Generated by Django 4.2.7 on 2024-08-31 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_tools", "0003_emailtemplate_valid_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="useremail",
            name="email_template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_emails",
                to="app_tools.emailtemplate",
            ),
        ),
    ]
