# Generated by Django 4.2.7 on 2024-09-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tools", "0004_useremail_email_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="useremail",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
