# Generated by Django 4.2.7 on 2024-07-31 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("lump_sum", "lump_sum"), ("split", "split")],
                        default="lump_sum",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="paymentterm",
            name="payment",
        ),
        migrations.DeleteModel(
            name="PaymentStyle",
        ),
        migrations.AddField(
            model_name="paymentterm",
            name="payment_plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_terms",
                to="app_finance.paymentplan",
            ),
            preserve_default=False,
        ),
    ]
