# Generated by Django 4.2.7 on 2024-08-02 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0002_paymentplan_remove_paymentterm_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentterm",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userpayment",
            name="payment_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_payments",
                to="app_finance.paymentmethod",
            ),
        ),
    ]
