# Generated by Django 4.2.7 on 2024-08-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0003_paymentterm_is_processed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="transaction_id",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
