# Generated by Django 4.2.7 on 2024-08-03 01:19

from django.db import migrations, models

import app_finance.models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0004_userpayment_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="payment_screenshot",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to=app_finance.models.get_tenant_specfic_folder_for_payment_ss,
            ),
        ),
    ]
