# Generated by Django 4.2.7 on 2024-08-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0025_alter_course_code"),
        ("app_finance", "0005_userpayment_payment_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="user_course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_payments",
                to="app_course.usercourse",
            ),
        ),
    ]
