# Generated by Django 4.2.7 on 2024-08-10 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0026_remove_course_payment_plan"),
        ("app_finance", "0006_userpayment_user_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplan",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_plans",
                to="app_course.course",
            ),
            preserve_default=False,
        ),
    ]
