# Generated by Django 4.2.7 on 2024-08-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0026_remove_course_payment_plan"),
        ("app_finance", "0008_alter_paymentplan_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentplan",
            options={},
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="name",
            field=models.CharField(default="a war yaung", max_length=512),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="paymentplan",
            unique_together={("name", "course")},
        ),
    ]
