# Generated by Django 4.2.7 on 2024-08-11 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0009_alter_paymentplan_options_paymentplan_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentterm",
            name="payment_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_terms",
                to="app_finance.paymentplan",
            ),
        ),
        migrations.AlterField(
            model_name="userpayment",
            name="payment_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_payments",
                to="app_finance.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="userpayment",
            name="payment_term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_payments",
                to="app_finance.paymentterm",
            ),
        ),
    ]
