# Generated by Django 4.2.7 on 2024-08-13 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0010_alter_paymentterm_payment_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="parent_payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_payments",
                to="app_finance.userpayment",
            ),
        ),
    ]
