# Generated by Django 4.2.7 on 2024-08-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0011_userpayment_parent_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="discount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
