# Generated by Django 4.2.7 on 2024-08-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0013_alter_userpayment_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpayment",
            name="reminder_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("first_sent", "first_sent"),
                    ("final_sent", "final_sent"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
