# Generated by Django 4.2.7 on 2024-08-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0014_alter_userpayment_reminder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="public_view",
            field=models.TextField(
                blank=True, help_text="This will be shown to public users", null=True
            ),
        ),
    ]
