# Generated by Django 4.2.7 on 2024-11-21 12:40

import app_finance.models
from django.db import migrations, models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0015_paymentmethod_public_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiverTransactionScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data",
                    models.ImageField(
                        storage=schedjuice_backend.storages.PrivateMediaStorage(),
                        upload_to=app_finance.models.get_tenant_specific_folder_for_receiver_ss,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
    ]
