# Generated by Django 4.2.7 on 2025-09-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0016_receivertransactionscreenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_user_count', models.PositiveIntegerField()),
                ('cost_per_account_at_creation', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
