# Generated by Django 4.2.7 on 2025-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0017_billing"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivertransactionscreenshot",
            name="text_data",
            field=models.JSONField(null=True),
        ),
    ]
