# Generated by Django 4.2.7 on 2025-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0018_receivertransactionscreenshot_text_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivertransactionscreenshot",
            name="amount",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="receivertransactionscreenshot",
            name="transaction_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
