# Generated by Django 4.2.7 on 2025-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0019_receivertransactionscreenshot_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivertransactionscreenshot",
            name="month",
            field=models.DateTimeField(null=True),
        ),
    ]
