# Generated by Django 4.2.7 on 2025-10-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0020_receivertransactionscreenshot_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivertransactionscreenshot",
            name="reject_reason",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="receivertransactionscreenshot",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("verified", "verified"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
