# Generated by Django 4.2.7 on 2025-10-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0021_receivertransactionscreenshot_reject_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receivertransactionscreenshot",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("verified", "verified"),
                    ("rejected", "rejected"),
                    ("extraction_failed", "extraction_failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
