# Generated by Django 4.2.7 on 2025-12-03 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0022_alter_receivertransactionscreenshot_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="paymentplan",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="paymentplan",
            name="course",
        ),
        migrations.RemoveField(
            model_name="paymentterm",
            name="payment_plan",
        ),
        migrations.RemoveField(
            model_name="userpayment",
            name="parent_payment",
        ),
        migrations.RemoveField(
            model_name="userpayment",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="userpayment",
            name="payment_term",
        ),
        migrations.RemoveField(
            model_name="userpayment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userpayment",
            name="user_course",
        ),
        migrations.RemoveField(
            model_name="userpayment",
            name="verified_by",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
        migrations.DeleteModel(
            name="PaymentPlan",
        ),
        migrations.DeleteModel(
            name="PaymentTerm",
        ),
        migrations.DeleteModel(
            name="UserPayment",
        ),
    ]
