# Generated by Django 4.2.7 on 2025-12-04 00:04

import app_finance.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_finance", "0023_alter_paymentplan_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "screenshot",
                    models.ImageField(
                        null=True,
                        storage=schedjuice_backend.storages.PrivateMediaStorage(),
                        upload_to=app_finance.models.get_tenant_specfic_folder_for_payment_ss,
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("text_data", models.JSONField(null=True)),
                ("transaction_id", models.CharField(max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cannot_extract", "cannot_extract"),
                            ("pending", "pending"),
                            ("verified", "verified"),
                            ("amount_mismatch", "amount_mismatch"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
    ]
