# Generated by Django 4.2.7 on 2025-12-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0026_rename_amount_userpayment_parsed_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("cannot_extract", "cannot_extract"),
                    ("awaiting_extraction", "awaiting_extraction"),
                    ("pending_verification", "pending_verification"),
                    ("verified", "verified"),
                    ("amount_mismatch", "amount_mismatch"),
                ],
                default="awaiting_extraction",
                max_length=20,
            ),
        ),
    ]
