# Generated by Django 4.2.7 on 2025-12-07 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_finance", "0030_receivertransactionscreenshot_amount_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpayment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
