# Generated by Django 4.2.7 on 2025-12-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0044_alter_event_date"),
        ("app_finance", "0032_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="course",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="user",
        ),
        migrations.DeleteModel(
            name="ReceiverTransactionScreenshot",
        ),
        migrations.RenameField(
            model_name="userpayment",
            old_name="user_provided_amount",
            new_name="invoiced_amount",
        ),
        migrations.RenameField(
            model_name="userpayment",
            old_name="user_provided_amount_currency",
            new_name="invoiced_amount_currency",
        ),
        migrations.AddField(
            model_name="userpayment",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_payments",
                to="app_course.course",
            ),
        ),
        migrations.AlterField(
            model_name="userpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "pending_payment"),
                    ("cannot_extract", "cannot_extract"),
                    ("awaiting_extraction", "awaiting_extraction"),
                    ("pending_verification", "pending_verification"),
                    ("duplicated", "duplicated"),
                    ("verified", "verified"),
                    ("amount_mismatch", "amount_mismatch"),
                ],
                default="awaiting_extraction",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
