# Generated by Django 4.2.7 on 2025-12-15 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0033_remove_invoice_course_remove_invoice_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentCourse",
        ),
    ]
