# Generated by Django 4.2.7 on 2025-12-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0034_delete_paymentcourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="issued_date",
            field=models.DateTimeField(null=True),
        ),
    ]
