# Generated by Django 4.2.7 on 2025-12-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0036_paymentplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplan",
            name="days_before_course_locked",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Number of days after the payment due date when the course gets locked for non-paying users",
            ),
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="early_payment_days",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Number of days before the course start date when users can start making payments",
            ),
        ),
    ]
