# Generated by Django 4.2.7 on 2025-12-29 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_course", "0046_course_student_count_course_teacher_count_and_more"),
        ("app_finance", "0037_paymentplan_days_before_course_locked_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpayment",
            options={},
        ),
        migrations.RenameField(
            model_name="userpayment",
            old_name="issued_date",
            new_name="billing_start_date",
        ),
        migrations.AddField(
            model_name="userpayment",
            name="billing_end_date",
            field=models.DateTimeField(null=True),
        ),
    ]
