# Generated by Django 4.2.7 on 2025-12-29 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0038_alter_userpayment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpayment",
            options={"ordering": ["id"]},
        ),
    ]
