# Generated by Django 4.2.7 on 2025-12-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0039_alter_userpayment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="remarks",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
