# Generated by Django 4.2.7 on 2026-01-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0040_userpayment_remarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "payment_bank",
                    models.CharField(
                        choices=[
                            ("KBZ", "KBZ"),
                            ("KPAY", "KPAY"),
                            ("CB", "CB"),
                            ("AYA", "AYA"),
                            ("YOMA", "YOMA"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="userpayment",
            name="date_on_screenshot",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="userpayment",
            name="description",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="userpayment",
            name="payment_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_payments",
                to="app_finance.paymentmethod",
            ),
        ),
    ]
