# Generated by Django 4.2.7 on 2026-01-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0041_paymentmethod_userpayment_date_on_screenshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="issued_at",
            field=models.DateTimeField(null=True),
        ),
    ]
