# Generated by Django 4.2.7 on 2026-01-19 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_finance", "0043_alter_paymentmethod_payment_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_user_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
