# Generated by Django 4.2.7 on 2026-01-30 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0044_userpayment_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpayment",
            old_name="text_data",
            new_name="json_ocr_data",
        ),
    ]
