# Generated by Django 4.2.7 on 2026-01-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0045_rename_text_data_userpayment_json_ocr_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="text_ocr_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
