# Generated by Django 4.2.7 on 2026-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0046_userpayment_text_ocr_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "pending_payment"),
                    ("cannot_extract", "cannot_extract"),
                    ("awaiting_extraction", "awaiting_extraction"),
                    ("awaiting_metadata_extraction", "awaiting_metadata_extraction"),
                    ("pending_verification", "pending_verification"),
                    ("duplicated", "duplicated"),
                    ("verified", "verified"),
                    ("amount_mismatch", "amount_mismatch"),
                ],
                default="pending_payment",
                max_length=100,
            ),
        ),
    ]
