# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0047_alter_userpayment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiverSideScreenshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.CharField(max_length=100)),
                ("is_matched", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
    ]
