# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0048_receiver_side_screenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiversidescreenshot",
            name="user_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receiver_side_screenshot",
                to="app_finance.userpayment",
            ),
        ),
    ]
