# Generated by Django 4.2 — UserPayment.verified_at for analytics and verification audit.

from django.db import migrations, models
from django.db.models import F


def backfill_verified_at(apps, schema_editor):
    UserPayment = apps.get_model("app_finance", "UserPayment")
    verified = "verified"
    UserPayment.objects.filter(status=verified).update(verified_at=F("updated_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0052_billing_billing_daet"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="verified_at",
            field=models.DateTimeField(
                null=True,
                blank=True,
                db_index=True,
                help_text="When the payment was first marked verified.",
            ),
        ),
        migrations.RunPython(backfill_verified_at, migrations.RunPython.noop),
    ]
