# Generated by Django 4.2.7 on 2026-04-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0053_userpayment_verified_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPaymentCoveredMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                (
                    "month_index",
                    models.PositiveSmallIntegerField(help_text="Calendar month 1–12."),
                ),
                (
                    "user_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covered_months",
                        to="app_finance.userpayment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["year", "month_index"],
                        name="app_finance_year_18e94a_idx",
                    ),
                    models.Index(
                        fields=["user_payment", "year", "month_index"],
                        name="app_finance_user_pa_adb9e8_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userpaymentcoveredmonth",
            constraint=models.UniqueConstraint(
                fields=("user_payment", "year", "month_index"),
                name="app_finance_userpaymentcoveredmonth_unique_month_per_payment",
            ),
        ),
    ]
