# Generated by Django 4.2.7 on 2026-05-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0054_user_payment_covered_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="payment_bank",
            field=models.CharField(
                choices=[
                    ("KBZ", "KBZ"),
                    ("KPAY", "KPAY"),
                    ("UAB", "UAB"),
                    ("CB", "CB"),
                    ("AYA", "AYA"),
                    ("YOMA", "YOMA"),
                    ("CASH", "CASH"),
                ],
                max_length=20,
            ),
        ),
    ]
