# Generated by Django 4.2.7 on 2026-06-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_finance", "0057_userpayment_installment_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "bank_type",
                    models.CharField(
                        choices=[
                            ("KBZ", "KBZ"),
                            ("KPAY", "KPAY"),
                            ("UAB", "UAB"),
                            ("CB", "CB"),
                            ("AYA", "AYA"),
                            ("YOMA", "YOMA"),
                            ("CASH", "CASH"),
                            ("MOB", "MOB"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_infos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="paymentinfo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="app_finance_paymentinfo_unique_default_per_user",
            ),
        ),
    ]
