# Generated by Django 4.2.7 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0058_payment_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinfo",
            name="account_name",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
    ]
