# Generated by Django 4.2.7 on 2026-06-29 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0059_paymentinfo_account_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentinfo",
            options={},
        ),
    ]
