# Generated by Django 4.2.7 on 2026-07-10 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0103_coursemembershipevent_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_finance", "0061_discount_enrollment_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPaymentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("issued_at", models.DateTimeField(null=True)),
                ("billing_start_date", models.DateTimeField(null=True)),
                ("billing_end_date", models.DateTimeField(null=True)),
                ("is_installment", models.BooleanField(default=False)),
                (
                    "installment_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional display percent for this installment (0–100).",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_payment_groups",
                        to="app_course.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_user_payment_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_payment_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="userpayment",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="app_finance.userpaymentgroup",
            ),
        ),
    ]
