# Generated by Django 4.2.7 on 2026-07-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0063_drop_userpayment_billing_window_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="bulk_min_courses",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="early_bird_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="eligibility_type",
            field=models.CharField(
                choices=[
                    ("none", "none"),
                    ("early_bird", "early_bird"),
                    ("loyalty", "loyalty"),
                    ("bulk", "bulk"),
                ],
                default="none",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="enrollmentdiscount",
            name="snapshot_bulk_min_courses",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollmentdiscount",
            name="snapshot_early_bird_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollmentdiscount",
            name="snapshot_eligibility_type",
            field=models.CharField(
                choices=[
                    ("none", "none"),
                    ("early_bird", "early_bird"),
                    ("loyalty", "loyalty"),
                    ("bulk", "bulk"),
                ],
                default="none",
                max_length=32,
            ),
        ),
    ]
