# Generated by Django 4.2.7 on 2026-07-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0065_userpayment_discount_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplan",
            name="billing_type",
            field=models.CharField(
                choices=[
                    ("per_period", "Per billing period"),
                    ("whole_term", "Whole term"),
                ],
                default="per_period",
                help_text="Whether `price` covers a single billing period or the whole course term",
                max_length=20,
            ),
        ),
    ]
