# Generated by Django 4.2.7 on 2026-07-14 04:00

import app_finance.models
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_finance", "0066_paymentplan_billing_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("refund", "refund"),
                            ("re_transfer", "re_transfer"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("USD", "US Dollar")],
                        default="USD",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=4,
                        default_currency="USD",
                        max_digits=19,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("note", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payment_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="app_finance.userpayment",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAdjustmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        storage=schedjuice_backend.storages.PrivateMediaStorage(),
                        upload_to=app_finance.models.get_tenant_specific_folder_for_payment_adjustments,
                    ),
                ),
                ("filename", models.CharField(max_length=5120)),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app_finance.paymentadjustment",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
