# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_finance", "0067_payment_adjustment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff user who first marked the payment verified, when known.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_user_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
