# Generated by Django 4.2.7 on 2026-07-20 14:50

import app_finance.models
from django.db import migrations, models
import django.db.models.deletion
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0068_staffpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffpayment",
            name="screenshot",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to=app_finance.models.get_tenant_specific_folder_for_staff_payment_ss,
            ),
        ),
        migrations.CreateModel(
            name="StaffPaymentProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        storage=schedjuice_backend.storages.PrivateMediaStorage(),
                        upload_to=app_finance.models.get_tenant_specific_folder_for_staff_payment_proofs,
                    ),
                ),
                ("filename", models.CharField(max_length=5120)),
                (
                    "staff_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="app_finance.staffpayment",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
