# Generated by Django 4.2.7 on 2026-07-21 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0068_userpayment_verified_by"),
        ("app_finance", "0070_staffpayment_pay_period"),
    ]

    operations = []
