# Generated by Django 4.2.7 on 2026-07-22 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0071_merge_20260722_1127"),
        ("app_finance", "0072_multi_discount_stacking"),
    ]

    operations = []
