# Generated by Django 4.2.7 on 2026-07-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0078_userpayment_discount_ids_set_on_create"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReceiptCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("next_sequence", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="userpayment",
            name="receipt_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="userpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("receipt_number__isnull", False)),
                fields=("receipt_number",),
                name="uniq_userpayment_receipt_number_non_null",
            ),
        ),
    ]
