# Generated by Django 4.2.7 on 2026-07-28 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_finance", "0080_userpaymentgroup_group_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField(unique=True)),
                (
                    "receipt_date",
                    models.DateTimeField(
                        help_text="Date printed on the receipt: earliest payment_date in the unit."
                    ),
                ),
                ("is_void", models.BooleanField(default=False)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff user whose verification completed this receipt.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_payment_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="userpayment",
            name="receipt",
            field=models.ForeignKey(
                blank=True,
                help_text="Issued receipt. Set on verification; all parts of a group share one.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="app_finance.paymentreceipt",
            ),
        ),
    ]
