# Generated by Django 4.2.7 on 2026-08-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0087_backfill_split_screenshot_group_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="ocr_event_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
