# Generated by Django 4.2.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_auth", "0040_alter_dataverificationrequest_requested_user_types_and_more"),
        ("app_course", "0059_usercourse_hourly_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.JSONField(
                        help_text="Structured payload: {text, mentions, ...} for rich content"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="app_course.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="app_auth.user",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="coursechatmessage",
            index=models.Index(
                fields=["course", "created_at"],
                name="app_chat_course_created_idx",
            ),
        ),
    ]
