# Generated by Django 4.2.7 on 2026-02-19 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="coursechatmessage",
            new_name="app_chat_co_course__57dd64_idx",
            old_name="app_chat_course_created_idx",
        ),
    ]
