# Generated by Django 4.2.7 on 2026-04-20 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_chat", "0003_coursechatmessage_reply_read_state"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="coursechatreadstate",
            new_name="app_chat_co_course__cc40d6_idx",
            old_name="app_chat_cochatread_course_user_idx",
        ),
    ]
