# Generated by Django 4.2.7 on 2026-04-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0043_user_custom_data"),
        ("app_chat", "0004_rename_app_chat_cochatread_course_user_idx_app_chat_co_course__cc40d6_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessageThread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user_high",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dm_threads_high",
                        to="app_auth.user",
                    ),
                ),
                (
                    "user_low",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dm_threads_low",
                        to="app_auth.user",
                    ),
                ),
            ],
            options={"indexes": [models.Index(fields=["user_low", "user_high"], name="app_chat_di_user_lo_93f1ca_idx")]},
        ),
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("content", models.JSONField(help_text="Structured payload: {text, mentions, attachments}")),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_messages_deleted",
                        to="app_auth.user",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="app_chat.directmessagethread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_messages",
                        to="app_auth.user",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["thread", "created_at"], name="app_chat_di_thread__c720db_idx")],
            },
        ),
        migrations.CreateModel(
            name="DirectMessageReadState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("last_read_message_id", models.BigIntegerField(blank=True, null=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_states",
                        to="app_chat.directmessagethread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_message_read_states",
                        to="app_auth.user",
                    ),
                ),
            ],
            options={"indexes": [models.Index(fields=["thread", "user"], name="app_chat_di_thread__ec3f31_idx")]},
        ),
        migrations.AddConstraint(
            model_name="directmessagethread",
            constraint=models.UniqueConstraint(fields=("user_low", "user_high"), name="uniq_dm_thread_user_pair"),
        ),
        migrations.AddConstraint(
            model_name="directmessagereadstate",
            constraint=models.UniqueConstraint(fields=("user", "thread"), name="uniq_dm_read_user_thread"),
        ),
    ]
