# Generated by Django 4.2.7 on 2026-05-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0005_dm_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='directmessage',
            new_name='app_chat_di_thread__51887d_idx',
            old_name='app_chat_di_thread__c720db_idx',
        ),
        migrations.RenameIndex(
            model_name='directmessagereadstate',
            new_name='app_chat_di_thread__8e13a1_idx',
            old_name='app_chat_di_thread__ec3f31_idx',
        ),
        migrations.RenameIndex(
            model_name='directmessagethread',
            new_name='app_chat_di_user_lo_45ae92_idx',
            old_name='app_chat_di_user_lo_93f1ca_idx',
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='directmessagereadstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='directmessagereadstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='directmessagethread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='directmessagethread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
