# Generated by Django 4.2.7 on 2026-05-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0043_user_custom_data"),
        ("app_chat", "0006_rename_app_chat_di_thread__c720db_idx_app_chat_di_thread__51887d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessageReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("emoji", models.CharField(max_length=10)),
                (
                    "course_chat_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="app_chat.coursechatmessage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_message_reactions",
                        to="app_auth.user",
                    ),
                ),
                (
                    "direct_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="app_chat.directmessage",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="chatmessagereaction",
            constraint=models.UniqueConstraint(
                fields=("created_by", "course_chat_message"),
                name="uniq_chat_reaction_user_course_msg",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessagereaction",
            constraint=models.UniqueConstraint(
                fields=("created_by", "direct_message"),
                name="uniq_chat_reaction_user_dm_msg",
            ),
        ),
    ]
