# Generated by Django 4.2.7 on 2026-06-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_chat", "0008_directmessage_reply_to"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatmessagereaction",
            name="uniq_chat_reaction_user_course_msg",
        ),
        migrations.RemoveConstraint(
            model_name="chatmessagereaction",
            name="uniq_chat_reaction_user_dm_msg",
        ),
        migrations.AddIndex(
            model_name="chatmessagereaction",
            index=models.Index(
                fields=["course_chat_message"], name="app_chat_ch_course__39f694_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessagereaction",
            index=models.Index(
                fields=["direct_message"], name="app_chat_ch_direct__2de3dc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessagereaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("course_chat_message__isnull", False)),
                fields=("created_by", "course_chat_message"),
                name="uniq_chat_reaction_user_course_msg",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessagereaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("direct_message__isnull", False)),
                fields=("created_by", "direct_message"),
                name="uniq_chat_reaction_user_dm_msg",
            ),
        ),
    ]
