from django.urls import path

from app_organization import views
from app_organization.id_card_template_views import (
    IdCardTemplateActivateView,
    IdCardTemplateDetailsView,
    IdCardTemplateListView,
)
from app_organization.mobile_version_views import MobileAppVersionCheckView

urlpatterns = [
    path(
        "mobile/app-version",
        MobileAppVersionCheckView.as_view(),
        name="mobile-app-version",
    ),
    path("user-tenants", views.UserTenantView.as_view(), name="user-tenants"),
    path(
        "organizations", views.OrganizationListView.as_view(), name="organization-list"
    ),
    path(
        "organizations/<int:obj_id>",
        views.OrganizationDetailsView.as_view(),
        name="organization-details",
    ),
    path(
        "organizations/<int:obj_id>/ai-settings",
        views.OrganizationAISettingsView.as_view(),
        name="organization-ai-settings",
    ),
    path(
        "organizations/<int:obj_id>/ai-usage",
        views.OrganizationAIUsageView.as_view(),
        name="organization-ai-usage",
    ),
    path(
        "organizations/<int:obj_id>/ai-usage/users",
        views.OrganizationAIUsageUsersView.as_view(),
        name="organization-ai-usage-users",
    ),
    path(
        "organizations/<int:obj_id>/billing",
        views.OrganizationBillingView.as_view(),
        name="organization-billing",
    ),
    path(
        "organizations/<int:obj_id>/platform-billing-config",
        views.OrganizationPlatformBillingConfigView.as_view(),
        name="organization-platform-billing-config",
    ),
    path(
        "organizations/<int:obj_id>/platform-invoices",
        views.OrganizationPlatformInvoiceListCreateView.as_view(),
        name="organization-platform-invoices",
    ),
    path(
        "platform-invoices/<int:invoice_id>",
        views.PlatformInvoiceDetailView.as_view(),
        name="platform-invoice-detail",
    ),
    path(
        "organizations/<int:obj_id>/ai-usage/failures",
        views.OrganizationAIUsageFailuresView.as_view(),
        name="organization-ai-usage-failures",
    ),
    path(
        "organizations/<int:obj_id>/ai-usage/failures/<int:request_log_id>",
        views.OrganizationAIUsageFailureResolveView.as_view(),
        name="organization-ai-usage-failure-resolve",
    ),
    path(
        "organizations/<int:obj_id>/ai-usage/requests",
        views.OrganizationAIUsageRequestsView.as_view(),
        name="organization-ai-usage-requests",
    ),
    path(
        "organizations/<int:obj_id>/ai-usage/analytics",
        views.OrganizationAIUsageAnalyticsView.as_view(),
        name="organization-ai-usage-analytics",
    ),
    path(
        "organizations/search",
        views.OrganizationSearchView.as_view(),
        name="organization-search",
    ),
    path(
        "organizations/public",
        views.OrganizationPublicView.as_view(),
        name="organization-public",
    ),
    path(
        "organizations/<int:obj_id>/admins/search",
        views.OrganizationAdminSearchView.as_view(),
        name="organization-admins-search",
    ),
    path(
        "organizations/<int:obj_id>/users/search",
        views.OrganizationUserSearchView.as_view(),
        name="organization-users-search",
    ),
    path(
        "organizations/<int:obj_id>/admins",
        views.OrganizationAdminListView.as_view(),
        name="organization-admins",
    ),
    path(
        "organizations/<int:org_id>/id-card-templates",
        IdCardTemplateListView.as_view(),
        name="organization-id-card-templates",
    ),
    path(
        "organizations/<int:org_id>/id-card-templates/<int:template_id>",
        IdCardTemplateDetailsView.as_view(),
        name="organization-id-card-template-details",
    ),
    path(
        "organizations/<int:org_id>/id-card-templates/<int:template_id>/activate",
        IdCardTemplateActivateView.as_view(),
        name="organization-id-card-template-activate",
    ),
]
