# Generated by Django 4.2.7 on 2024-08-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
