# Generated by Django 4.2.7 on 2025-03-06 22:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0030_course_default_daily_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_attendance", "0002_attendance_note"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Attendance",
            new_name="UserEvent",
        ),
    ]
