# Generated by Django 4.2.7 on 2025-03-06 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_attendance", "0003_rename_attendance_userevent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userevent",
            old_name="note",
            new_name="attendance_note",
        ),
        migrations.RenameField(
            model_name="userevent",
            old_name="status",
            new_name="attendance_status",
        ),
    ]
