# Generated by Django 4.2.7 on 2025-03-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attendance", "0004_rename_note_userevent_attendance_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
