# Generated by Django 4.2.7 on 2025-04-26 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_attendance", "0005_userevent_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
