# Generated by Django 4.2.7 on 2025-08-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attendance", "0006_alter_userevent_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="attendance_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
