# Generated by Django 4.2.7 on 2025-10-03 09:57

import app_attendance.models
from django.db import migrations, models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_attendance", "0007_userevent_attendance_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="checkin_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to=app_attendance.models.get_tenant_specific_upload_folder_for_checkin_image,
            ),
        ),
        migrations.AddField(
            model_name="userevent",
            name="checkin_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userevent",
            name="checkout_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
