# Generated by Django 4.2.7 on 2025-12-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_attendance",
            "0008_userevent_checkin_image_userevent_checkin_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="is_extra_class",
            field=models.BooleanField(default=False),
        ),
    ]
