# Generated by Django 4.2.7 on 2026-01-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attendance", "0009_userevent_is_extra_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="hourly_rate_at_calculation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
