# Generated by Django 4.2.7 on 2026-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attendance", "0010_userevent_hourly_rate_at_calculation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="student_bonus_rate_at_calculation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="userevent",
            name="student_count_in_course_at_calculation",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
