# Generated by Django 4.2.7 on 2026-03-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attendance", "0011_userevent_student_bonus_rate_at_calculation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="per_hour_price_at_calculation",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Snapshot of course payment plan per-hour price when payroll fields are frozen (cash-flow income).",
                max_digits=19,
                null=True,
            ),
        ),
    ]
