# Generated by Django 4.2.7 on 2026-06-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attendance", "0012_userevent_per_hour_price_at_calculation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="today_activities",
            field=models.TextField(blank=True, null=True),
        ),
    ]
