# Generated by Django 4.2.7 on 2026-07-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_attendance", "0015_attendancechangeevent"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="attendancechangeevent",
            new_name="app_attenda_user_ev_d880d7_idx",
            old_name="app_attenda_user_ev_6f8b2d_idx",
        ),
        migrations.AddField(
            model_name="userevent",
            name="event_time_from_at_calculation",
            field=models.DateTimeField(
                blank=True,
                help_text="Frozen Event session start (UTC) at first teacher check-in; used for billable hours.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userevent",
            name="event_time_to_at_calculation",
            field=models.DateTimeField(
                blank=True,
                help_text="Frozen Event session end (UTC) at first teacher check-in; used for billable hours.",
                null=True,
            ),
        ),
    ]
