# Generated by Django 4.2.7 on 2026-09-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0017_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='attendance_status',
            field=models.CharField(choices=[('unregistered', 'Unregistered'), ('present', 'Present'), ('absent', 'Absent'), ('absent_with_leave', 'Absent with leave'), ('late', 'Late')], default='unregistered', max_length=32),
        ),
    ]
