diff a/schedjuice-reimagined-be/Dockerfile-broker b/schedjuice-reimagined-be/Dockerfile-broker	(rejected hunks)
@@ -1,4 +1,4 @@
-FROM python:3.10.7
+FROM python:3.10-slim-bookworm
 
 ENV PYTHONFAULTHANDLER=1
 ENV PYTHONUNBUFFERED=1
@@ -9,7 +9,7 @@ ENV PIP_DISABLE_PIP_VERSION_CHECK=1
 ENV PIP_DEFAULT_TIMEOUT=100
 
 RUN apt-get update && \
-    apt-get install -y libxml2-dev libxslt-dev && \
+    apt-get install -y --no-install-recommends git libxml2-dev libxslt-dev && \
     rm -rf /var/lib/apt/lists/*
 
 WORKDIR /app
