# Generated by Django 4.2.7 on 2024-11-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_library", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookauthor",
            name="author",
        ),
        migrations.RemoveField(
            model_name="bookauthor",
            name="book",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="BookAuthor",
        ),
    ]
