from django.urls import path

from app_attendance import leave_request_views, views

urlpatterns = [
    path("attendances", views.AttendanceListView.as_view(), name="attendance-list"),
    path(
        "attendances/<int:obj_id>",
        views.AttendanceDetailsView.as_view(),
        name="attendance-details",
    ),
    path(
        "attendances/search",
        views.AttendanceSearchView.as_view(),
        name="attendance-search",
    ),
    path(
        "attendances/get-by-event/<int:event_id>",
        views.AttendanceByEvent.as_view(),
        name="attendance-by-event",
    ),
    path(
        "attendances/marking-roster/<int:event_id>",
        views.AttendanceMarkingRosterView.as_view(),
        name="attendance-marking-roster",
    ),
    path(
        "attendances/monthly-attendance/<int:course_id>/<str:date>",
        views.MonthlyAttendanceView.as_view(),
        name="monthly-attendance",
    ),
    path(
        "attendances/course-summary/<int:course_id>",
        views.CourseAttendanceSummaryView.as_view(),
        name="course-attendance-summary",
    ),
    path(
        "attendances/user-checkin/open-session",
        views.UserOpenCheckinSessionView.as_view(),
        name="teacher-checkin-open-session",
    ),
    path(
        "attendances/user-checkin/<int:course_id>/cancel",
        views.UserCheckinCancelView.as_view(),
        name="teacher-checkin-cancel",
    ),
    path(
        "attendances/user-checkin/<int:course_id>",
        views.UserCheckinView.as_view(),
        name="teacher-checkin",
    ),
    path(
        "attendances/god-view/search",
        views.AttendanceGodViewSearchView.as_view(),
        name="attendance-god-view-search",
    ),
    path(
        "attendances/<int:obj_id>/self-correction",
        views.AttendanceSelfCorrectionView.as_view(),
        name="attendance-self-correction",
    ),
    path(
        "attendances/<int:obj_id>/corrections",
        views.AttendanceCorrectionsView.as_view(),
        name="attendance-corrections",
    ),
    path(
        "attendances/god-view/details",
        views.AttendanceGodViewDetailView.as_view(),
        name="attendance-god-view-details",
    ),
    path(
        "leave-requests",
        leave_request_views.LeaveRequestListCreateView.as_view(),
        name="leave-request-list-create",
    ),
    path(
        "leave-requests/<int:obj_id>",
        leave_request_views.LeaveRequestDetailView.as_view(),
        name="leave-request-detail",
    ),
    path(
        "leave-requests/<int:obj_id>/cancel",
        leave_request_views.LeaveRequestCancelView.as_view(),
        name="leave-request-cancel",
    ),
    path(
        "leave-requests/<int:obj_id>/approve",
        leave_request_views.LeaveRequestApproveView.as_view(),
        name="leave-request-approve",
    ),
    path(
        "leave-requests/<int:obj_id>/deny",
        leave_request_views.LeaveRequestDenyView.as_view(),
        name="leave-request-deny",
    ),
]
