# Generated by Django 4.2.7 on 2026-08-06 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationWeeklyWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.JSONField(default=dict)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_weekly_whitelist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consultation weekly whitelist',
            },
        ),
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('student_name', models.CharField(max_length=512)),
                ('student_email', models.EmailField(max_length=254)),
                ('meeting_link', models.CharField(blank=True, max_length=2048)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=512)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=16)),
                ('cancel_token_hash', models.CharField(blank=True, max_length=128)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('consultant', 'Consultant'), ('student', 'Student')], max_length=16, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='consultationbooking',
            constraint=models.UniqueConstraint(fields=('consultant', 'scheduled_at'), name='uniq_consultation_booking_consultant_scheduled_at'),
        ),
    ]
