# Generated by Django 4.2.7 on 2026-04-26 06:42

import app_quiz_v3.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_quiz_v3", "0010_fill_blank_choice_mode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("SINGLE_CHOICE", "Single choice"),
                    ("MULTIPLE_CHOICE", "Multiple choice"),
                    ("FILL_IN_BLANK", "Fill in the blank"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="questionfillblankacceptableanswer",
            name="body",
            field=models.JSONField(default=app_quiz_v3.models._empty_tiptap_doc),
        ),
        migrations.AlterField(
            model_name="questionoption",
            name="body",
            field=models.JSONField(default=app_quiz_v3.models._empty_tiptap_doc),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="intro_body",
            field=models.JSONField(default=app_quiz_v3.models._empty_tiptap_doc),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="outro_body",
            field=models.JSONField(default=app_quiz_v3.models._empty_tiptap_doc),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="overdue_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
