# Generated by Django 4.2.7 on 2023-11-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="Some text under the title",
                max_length=200,
                null=True,
            ),
        ),
    ]
