# Generated by Django 4.2.7 on 2023-11-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0002_organization_tagline"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
