# Generated by Django 4.2.7 on 2023-11-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0003_organization_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="app_id",
            field=models.CharField(
                blank=True, help_text="Some long guid", max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="authority",
            field=models.CharField(
                blank=True,
                help_text="https://login.microsoftonline.com/domain.onmicrosoft.com",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="certificate_id",
            field=models.CharField(
                blank=True, help_text="Certificate's guid", max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="client_secret",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_owner_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_microsoft_on",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="private_key",
            field=models.FileField(
                help_text="Private key to encrypt data sent to Microsoft",
                null=True,
                upload_to="certificates",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="staff_license_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="student_license_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="tenant_id",
            field=models.CharField(
                blank=True, help_text="Tenant's guid", max_length=512, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="thumbprint",
            field=models.CharField(
                blank=True,
                help_text="Certificate thumbprint",
                max_length=512,
                null=True,
            ),
        ),
    ]
