# Generated by Django 4.2.7 on 2023-11-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_organization",
            "0004_organization_app_id_organization_authority_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="private_key",
            field=models.BinaryField(
                help_text="Private key to encrypt data sent to Microsoft", null=True
            ),
        ),
    ]
