# Generated by Django 4.2.7 on 2023-11-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0005_alter_organization_private_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="private_key",
            field=models.FileField(
                help_text="Private key to encrypt data sent to Microsoft",
                null=True,
                upload_to="",
            ),
        ),
    ]
