# Generated by Django 4.2.7 on 2023-12-03 11:58

from django.db import migrations, models

import app_organization.models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0007_alter_organization_private_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="private_key",
            field=models.FileField(
                help_text="Private key to encrypt data sent to Microsoft",
                null=True,
                upload_to=app_organization.models.get_upload_to_path_for_certs,
            ),
        ),
    ]
