# Generated by Django 4.2.7 on 2023-12-06 10:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0009_alter_organization_private_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="available_domains",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=512), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
