# Generated by Django 4.2.7 on 2024-06-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0010_organization_available_domains"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="theme",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
