# Generated by Django 4.2.7 on 2024-07-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0011_organization_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_homepage_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
