# Generated by Django 4.2.7 on 2024-08-04 09:06

from django.db import migrations, models

import app_organization.models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0012_organization_is_homepage_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="default_cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to=app_organization.models.get_upload_to_path_for_cover_image,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_student_login_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
