# Generated by Django 4.2.7 on 2024-11-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0013_organization_default_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_library_disabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="library_title",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
