# Generated by Django 4.2.7 on 2024-11-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0014_organization_is_library_disabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="library_title",
            field=models.CharField(
                blank=True, default="Library", max_length=512, null=True
            ),
        ),
    ]
