# Generated by Django 4.2.7 on 2024-11-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0015_alter_organization_library_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="library_title",
            field=models.CharField(default="Library", max_length=512),
        ),
    ]
