# Generated by Django 4.2.7 on 2025-08-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0016_alter_organization_library_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
