# Generated by Django 4.2.7 on 2025-09-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0018_organization_grace_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cost_per_account_per_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
