# Generated by Django 4.2.7 on 2025-10-16 12:21

import app_organization.models
from django.db import migrations, models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0019_organization_cost_per_account_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PublicMediaStorage(),
                upload_to=app_organization.models.get_upload_to_path_for_logos,
            ),
        ),
    ]
