# Generated by Django 4.2.7 on 2025-10-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0019_organization_cost_per_account_per_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="timezone",
            field=models.CharField(default="Asia/Rangoon", max_length=64),
        ),
    ]
