# Generated by Django 4.2.7 on 2025-10-26 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0020_organization_logo"),
        ("app_organization", "0020_organization_timezone"),
    ]

    operations = []
