# Generated by Django 4.2.7 on 2025-11-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0021_merge_20251026_0022"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_building_checkin_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
