# Generated by Django 4.2.7 on 2025-11-22 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0022_organization_is_building_checkin_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="grace_period",
            new_name="alumni_grace_period_day",
        ),
    ]
