# Generated by Django 4.2.7 on 2025-11-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_organization",
            "0023_rename_grace_period_organization_alumni_grace_period_day",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="checkin_grace_period_minute",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
