# Generated by Django 4.2.7 on 2025-11-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0024_organization_checkin_grace_period_minute"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_hr_fields_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_payroll_calculation_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
