# Generated by Django 4.2.7 on 2025-11-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0025_organization_is_hr_fields_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="can_teacher_create_course",
            field=models.BooleanField(default=False),
        ),
    ]
