# Generated by Django 4.2.7 on 2025-12-02 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0026_organization_can_teacher_create_course"),
        ("app_organization", "0026_organization_can_teacher_see_self_earnings"),
    ]

    operations = []
