# Generated by Django 4.2.7 on 2025-12-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0027_merge_20251202_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="transaction_screenshot_strategy",
            field=models.CharField(
                choices=[
                    ("user_upload", "user_upload"),
                    ("admin_upload", "admin_upload"),
                ],
                default="user_upload",
                max_length=20,
            ),
        ),
    ]
