# Generated by Django 4.2.7 on 2025-12-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0028_organization_transaction_screenshot_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="course_price",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="discount_course_price",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="invoice_generation_strategy",
            field=models.CharField(
                choices=[("tr_phillips", "tr_phillips")],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
    ]
