# Generated by Django 4.2.7 on 2025-12-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0029_organization_course_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="invoice_generation_strategy",
            field=models.CharField(
                choices=[("tr_phillips_style", "tr_phillips_style")],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
    ]
