# Generated by Django 4.2.7 on 2025-12-18 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0030_alter_organization_invoice_generation_strategy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="course_price",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="discount_course_price",
        ),
    ]
