# Generated by Django 4.2.7 on 2025-12-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0031_remove_organization_course_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="invoice_generation_interval_days",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
