# Generated by Django 4.2.7 on 2026-01-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0032_organization_invoice_generation_interval_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="report_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TR_SU_STYLE", "TR_SU_STYLE"),
                    ("TR_PHILLIPS_STYLE", "TR_PHILLIPS_STYLE"),
                ],
                max_length=40,
                null=True,
            ),
        ),
    ]
