# Generated by Django 4.2.7 on 2026-03-15 08:32

import app_organization.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0038_organization_course_fields_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="course_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=app_organization.models.get_default_course_fields,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="default_owner_id",
            field=models.CharField(
                blank=True,
                help_text="Azure AD user object ID of the meeting organizer (Entra > Users > [user] > Object ID). Must NOT be the Application (client) ID from app registration.",
                max_length=512,
                null=True,
            ),
        ),
    ]
