# Generated by Django 4.2.7 on 2026-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0039_alter_organization_course_fields_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="currency_fullname",
            field=models.CharField(default="Myanmar Kyat", max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="currency_iso4217",
            field=models.CharField(default="MMK", max_length=10),
        ),
        migrations.AddField(
            model_name="organization",
            name="currency_symbol",
            field=models.CharField(default="Ks", max_length=10),
        ),
    ]
