# Generated by Django 4.2.7 on 2026-04-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_organization",
            "0045_organization_max_custom_field_definitions_per_entity",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoomAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_id",
                    models.CharField(
                        help_text="External Zoom account_id returned by /v2/users/me on connect.",
                        max_length=128,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "authorized_by_zoom_user_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Zoom user_id of the admin who installed the app for this account.",
                        max_length=128,
                    ),
                ),
                (
                    "authorized_by_email",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Email of the admin who installed the app (display only).",
                        max_length=320,
                    ),
                ),
                ("access_token_ct", models.TextField(blank=True, default="")),
                ("refresh_token_ct", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "default_host_zoom_user_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Zoom user_id under which course meetings are scheduled.",
                        max_length=128,
                    ),
                ),
                (
                    "default_host_email",
                    models.CharField(blank=True, default="", max_length=320),
                ),
                (
                    "default_host_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("needs_reconnect", "Needs reconnect"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zoom_accounts",
                        to="app_organization.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="ix_zoom_account_org_status",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="zoomaccount",
            constraint=models.UniqueConstraint(
                fields=("organization", "account_id"),
                name="uniq_zoom_account_org_account_id",
            ),
        ),
    ]
