# Generated by Django 4.2.7 on 2026-05-22 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0047_organization_teacher_reminders"),
        ("app_organization", "0048_remove_recording_sync_models"),
    ]

    operations = []
