# Generated by Django 4.2.7 on 2026-06-03 13:01

import app_organization.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0048_remove_recording_sync_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="course_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=app_organization.models.get_default_course_fields,
                null=True,
                size=None,
            ),
        ),
    ]
