# Generated by Django 4.2.7 on 2026-05-23 09:24

import app_organization.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0049_merge_20260523_0102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="course_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=app_organization.models.get_default_course_fields,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="is_teacher_payment_consultation_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When True, FM/HM teacher payment-consultation reminders are enabled.",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="teacher_reminder_escalation_user_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Escalation recipient (tenant user id); blank skips escalation mail.",
                null=True,
            ),
        ),
    ]
