# Generated by Django 4.2.7 on 2026-06-03 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0049_alter_organization_course_fields"),
        ("app_organization", "0051_remove_teacher_payment_consultation_fields"),
    ]

    operations = []
