# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0053_organization_is_teams_creation_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="delegated_account_object_id",
            field=models.CharField(
                blank=True,
                help_text="Entra object ID of delegated_account_upn. Used for /users/{id}/ paths in delegated meeting flows. Falls back to STAFFY_AZURE_OBJECT_ID env when blank.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="delegated_account_password",
            field=models.CharField(
                blank=True,
                help_text="Password for delegated_account_upn. Falls back to STAFFY_PASSWORD env when blank.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="delegated_account_upn",
            field=models.CharField(
                blank=True,
                help_text="Entra sign-in UPN for delegated Graph (password-grant) flows. Falls back to STAFFY_DELEGATED_UPN env when blank.",
                max_length=512,
                null=True,
            ),
        ),
    ]
