# Generated by Django 4.2.7 on 2026-06-21

import app_organization.models
import schedjuice_backend.storages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0058_organization_telegram_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="id_card_org_name",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="id_card_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PublicMediaStorage(),
                upload_to=app_organization.models.get_upload_to_path_for_logos,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="id_card_staff_accent",
            field=models.CharField(default="#5ea37e", max_length=9),
        ),
        migrations.AddField(
            model_name="organization",
            name="id_card_student_accent",
            field=models.CharField(default="#d97706", max_length=9),
        ),
    ]
