# Generated by Django 4.2.7 on 2026-06-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0059_organization_id_card_branding"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                help_text="Demo/sandbox tenant provisioned by app_demo; exclude from billing.",
            ),
        ),
    ]
