# Generated by Django 4.2.7 on 2026-06-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0060_organization_is_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="campus_checkin_verification_mode",
            field=models.CharField(
                choices=[
                    ("geo_with_selfie_fallback", "geo_with_selfie_fallback"),
                    ("geo_only", "geo_only"),
                    ("selfie_only", "selfie_only"),
                ],
                default="geo_with_selfie_fallback",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_session_checkin_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
