# Generated by Django 4.2.7 on 2026-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0061_organization_campus_checkin_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronHealthAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("schema_name", models.CharField(max_length=63)),
                ("log_command_name", models.CharField(max_length=256)),
                ("alert_type", models.CharField(max_length=32)),
                ("last_alerted_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PlatformOpsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("discord_webhook_url_ct", models.TextField(blank=True, default="")),
                (
                    "discord_webhook_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="cronhealthalert",
            constraint=models.UniqueConstraint(
                fields=("schema_name", "log_command_name", "alert_type"),
                name="uniq_cron_health_alert",
            ),
        ),
    ]
