# Generated by Django 4.2.7 on 2026-06-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0062_platform_ops_settings_and_cron_health_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_staff_points_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When True, staff points ledger (multi-currency) is available.",
            ),
        ),
    ]
