# Generated by Django 4.2.7 on 2026-06-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0064_organization_ai_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformopssettings",
            name="vimeo_access_token_ct",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="platformopssettings",
            name="vimeo_folder_uri",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="platformopssettings",
            name="vimeo_settings_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
