# Generated by Django 4.2.7 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0069_grandfather_teams_attendance_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileAppVersionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("schedjuice", "Schedjuice"),
                            ("teachersucenter", "TeacherSuCenter"),
                            ("sdec", "SDEC"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")],
                        max_length=16,
                    ),
                ),
                ("minimum_version", models.CharField(max_length=32)),
                (
                    "recommended_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("latest_version", models.CharField(max_length=32)),
                (
                    "store_url",
                    models.URLField(blank=True, default="", max_length=512),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["variant", "platform"],
            },
        ),
        migrations.AddConstraint(
            model_name="mobileappversionpolicy",
            constraint=models.UniqueConstraint(
                fields=("variant", "platform"),
                name="uniq_mobile_app_version_policy",
            ),
        ),
    ]
