# Generated by Django 4.2.7 on 2026-07-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0069_grandfather_teams_attendance_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="ai_default_user_monthly_usd_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Default monthly USD cap per user. Null = platform default ($1).",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="use_teacher_session_checkin",
            field=models.BooleanField(
                default=True, help_text="Track teacher per-session check-in with photo."
            ),
        ),
    ]
