# Generated by Django 4.2.7 on 2026-07-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0070_mobileappversionpolicy'),
        ('app_organization', '0070_organization_ai_default_user_monthly_usd_limit'),
    ]

    operations = [
    ]
