# Generated by Django 4.2.7 on 2026-07-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0072_organization_allow_teacher_checkin_history_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notify_issue_observers_on_status_change',
            field=models.BooleanField(default=True, help_text='When True, email issue observers when an issue moves to a new status.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='notify_lead_observers_on_status_change',
            field=models.BooleanField(default=True, help_text='When True, email lead observers when a lead moves to a new status.'),
        ),
    ]
