# Generated by Django 4.2.7 on 2026-07-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0073_board_observer_notify_toggles"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_payment_plan_mandatory",
            field=models.BooleanField(
                default=False,
                help_text="When True, courses must have a payment_plan. Use for schools that rely on discounts, installments, and invoicing.",
            ),
        ),
    ]
