# Generated by Django 4.2.7 on 2026-07-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0074_is_payment_plan_mandatory"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_legacy_discount_visible",
            field=models.BooleanField(
                default=False,
                help_text="When True, show legacy PaymentPlan discount_price and per_hour_price fields in admin UI.",
            ),
        ),
    ]
