# Generated by Django 4.2.7 on 2026-07-18 13:15

from django.db import migrations, models


def forwards_set_legacy_packs(apps, schema_editor):
    Organization = apps.get_model("app_organization", "Organization")
    legacy = [
        "course_counts",
        "course_queries",
        "roster_read",
        "roster_write",
        "finance",
        "staff_points",
    ]
    for org in Organization.objects.all().iterator():
        val = org.ai_enabled_packs
        if val is None or val == []:
            org.ai_enabled_packs = legacy
            org.save(update_fields=["ai_enabled_packs"])


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_organization",
            "0076_organization_teaching_subjects_allow_level_category_search",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="ai_enabled_packs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI capability pack ids enabled for this org (core always on).",
            ),
        ),
        migrations.RunPython(forwards_set_legacy_packs, backwards_noop),
    ]
