# Generated by Django 4.2.7 on 2026-07-18 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0077_organization_ai_enabled_packs"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="default_session_duration_minutes",
            field=models.PositiveIntegerField(
                default=90,
                help_text="Default class session duration in minutes for simple scheduling UI.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_session_start_time",
            field=models.TimeField(
                default=datetime.time(19, 0),
                help_text="Default class session start time for simple scheduling UI.",
            ),
        ),
    ]
