# Generated by Django 4.2.7 on 2026-07-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0078_organization_default_session_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="time_display_format",
            field=models.CharField(
                choices=[("12h", "12-hour"), ("24h", "24-hour")],
                default="12h",
                help_text="How times are shown in the app UI (pickers and labels).",
                max_length=3,
            ),
        ),
    ]
