# Generated by Django 4.2.7 on 2026-07-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0078_organization_default_session_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="auto_assign_creator_as_main_teacher",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When True, if the course creator has exactly one role and it is teacher, "
                    "assign them as MAIN_TEACHER on the course and all of its events."
                ),
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_course_role_enabled",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "When False, teacher assignments ignore course-role choice and force the "
                    "tenant's MAIN_TEACHER AssignedAsRole. Errors if no MT role exists."
                ),
            ),
        ),
    ]
