# Generated by Django 4.2.7 on 2026-07-21 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0079_auto_assign_creator_mt_and_course_roles"),
        ("app_organization", "0079_organization_time_display_format"),
    ]

    operations = []
