# Generated by Django 4.2.7 on 2026-07-23 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0081_organization_is_telegram_login_on"),
        ("app_organization", "0082_wd_we_boolean_remove_course_fields"),
    ]

    operations = []
