# Generated by Django 4.2.7 on 2026-07-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0083_merge_20260723_1242"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_exam_board_in_course_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When True, show exam session and exam board on course forms "
                    "and require them on create/update."
                ),
            ),
        ),
    ]
