# Generated by Django 4.2.7 on 2026-07-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0083_id_card_template_back'),
        ('app_organization', '0084_organization_is_exam_board_in_course_enabled'),
    ]

    operations = [
    ]
