# Generated by Django 4.2.7 on 2026-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0086_organization_is_course_id_card_expiry_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_substitute_teachers_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Allow course roles to be marked as substitute roles. Substitute assignments pick specific session dates and can auto-expire after the last one.",
            ),
        ),
    ]
