# Generated by Django 4.2.7 on 2026-07-30 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0088_organization_report_style_excellent_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="MicrosoftDelegatedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authorized_upn",
                    models.CharField(blank=True, default="", max_length=320),
                ),
                (
                    "authorized_object_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("msal_cache_ct", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("needs_reconnect", "Needs reconnect"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microsoft_delegated_account",
                        to="app_organization.organization",
                    ),
                ),
            ],
            options={
                "db_table": "app_organization_microsoftdelegatedaccount",
            },
        ),
    ]
