# Generated by Django 4.2.7 on 2026-08-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0092_googlecalendarpushchannel"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_crm_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When True, CRM (Leads and Issues) is visible in the app.",
            ),
        ),
    ]
