# Generated by Django 4.2.7 on 2026-08-14 18:30

import app_organization.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_organization", "0093_organization_is_crm_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="idcardtemplate",
            name="background_transform",
            field=models.JSONField(
                blank=True,
                default=app_organization.models.default_id_card_background_transform,
            ),
        ),
    ]
