# Generated by Django 4.2.7 on 2026-09-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organization', '0102_organization_allow_teacher_checkin_cancellation'),
        ('app_organization', '0102_organization_is_mobile_id_card_enabled'),
    ]

    operations = [
    ]
