# Generated by Django 4.2.7 on 2026-09-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_organization", "0103_merge_20260903_0102"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_single_mobile_device_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When True, each user may have at most one active native mobile "
                    "app session; a new mobile login revokes other mobile sessions."
                ),
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="single_mobile_device_enabled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When single mobile device policy was last enabled.",
                null=True,
            ),
        ),
    ]
