# Generated by Django 4.2.7 on 2024-08-21 05:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_wiki", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="item",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="item",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="item",
            name="is_folder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="app_wiki.item",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("name", "parent")},
        ),
        migrations.RemoveField(
            model_name="item",
            name="folder",
        ),
        migrations.DeleteModel(
            name="Folder",
        ),
    ]
