# Generated by Django 4.2.7 on 2024-08-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_wiki",
            "0002_alter_item_unique_together_item_code_item_is_folder_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[("content", "content"), ("link", "link")],
                default="content",
                max_length=64,
            ),
        ),
    ]
