# Generated by Django 4.2.7 on 2024-08-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_wiki", "0003_item_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[("content", "content"), ("link", "link")], max_length=64
            ),
        ),
    ]
