# Generated by Django 4.2.7 on 2024-08-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_wiki", "0004_alter_item_item_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="item",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("name", "parent"), name="unique_name_parent"
            ),
        ),
    ]
