# Generated by Django 4.2.7 on 2024-08-21 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_wiki", "0005_alter_item_unique_together_item_unique_name_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveConstraint(
            model_name="item",
            name="unique_name_parent",
        ),
    ]
