# Generated by Django 4.2.7 on 2024-08-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_wiki", "0006_alter_item_options_remove_item_unique_name_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[("content", "content"), ("link", "link")],
                max_length=64,
                null=True,
            ),
        ),
    ]
