# Generated by Django 4.2.7 on 2024-08-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_wiki", "0007_alter_item_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="content",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
