# Generated by Django 4.2.7 on 2025-10-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_wiki", "0008_alter_item_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[("file", "file"), ("content", "content"), ("link", "link")],
                max_length=64,
                null=True,
            ),
        ),
    ]
