# Generated by Django 4.2.7 on 2023-11-13 12:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organization",
        ),
    ]
