# Generated by Django 4.2.7 on 2023-11-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0002_remove_user_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="microsoft_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
