# Generated by Django 4.2.7 on 2023-12-06 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0003_user_microsoft_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="alternative_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "male"),
                    ("FEMALE", "female"),
                    ("NON_BINARY", "non_binary"),
                    ("OTHER", "other"),
                ],
                default="male",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="09223", max_length=32),
            preserve_default=False,
        ),
    ]
