# Generated by Django 4.2.7 on 2024-02-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0004_user_alternative_name_user_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="placeholder", max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="communication_email",
            field=models.EmailField(
                default="placeholder@placeholder.com", max_length=254
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="house_number",
            field=models.CharField(default="placeholder", max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(default="placeholder", max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="street",
            field=models.CharField(default="placeholder", max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="township",
            field=models.CharField(default="placeholder", max_length=512),
            preserve_default=False,
        ),
    ]
