# Generated by Django 4.2.7 on 2024-02-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_auth",
            "0005_user_city_user_communication_email_user_house_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(default="placeholder", max_length=512),
            preserve_default=False,
        ),
    ]
