# Generated by Django 4.2.7 on 2024-07-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0006_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_view_mode",
            field=models.CharField(
                choices=[("table", "table"), ("card", "card")],
                default="card",
                max_length=64,
            ),
        ),
    ]
