# Generated by Django 4.2.7 on 2024-07-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0008_user_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images"),
        ),
    ]
