# Generated by Django 4.2.7 on 2024-07-17 13:31

from django.db import migrations, models

import app_auth.models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0009_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to=app_auth.models.get_tenant_specific_upload_folder_for_profile,
            ),
        ),
    ]
