# Generated by Django 4.2.7 on 2024-07-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0011_passwordresetrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordresetrequest",
            name="user",
        ),
        migrations.AddField(
            model_name="passwordresetrequest",
            name="email",
            field=models.EmailField(default="ok@ok.com", max_length=254),
            preserve_default=False,
        ),
    ]
