# Generated by Django 4.2.7 on 2024-07-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0012_remove_passwordresetrequest_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_password_change_required",
            field=models.BooleanField(default=True),
        ),
    ]
