# Generated by Django 4.2.7 on 2024-07-29 10:38

from django.db import migrations, models

import app_auth.models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0013_user_is_password_change_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("settings", models.JSONField()),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to=app_auth.models.get_tenant_specific_upload_folder_for_cover,
            ),
        ),
    ]
