# Generated by Django 4.2.7 on 2024-07-29 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0014_visibility_user_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="visibility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="app_auth.visibility",
            ),
        ),
        migrations.AddField(
            model_name="visibility",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visibilities",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
