# Generated by Django 4.2.7 on 2024-07-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0015_user_visibility_visibility_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="visibility",
            name="name",
            field=models.CharField(default="ok", max_length=512, unique=True),
            preserve_default=False,
        ),
    ]
