# Generated by Django 4.2.7 on 2024-07-30 18:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0016_visibility_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="visibility",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
