# Generated by Django 4.2.7 on 2024-08-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0017_visibility_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visibility",
            name="roles",
        ),
        migrations.AddField(
            model_name="visibility",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "superadmin"),
                    ("admin", "admin"),
                    ("manager", "manager"),
                    ("teacher", "teacher"),
                    ("student", "student"),
                ],
                default="student",
                max_length=32,
            ),
            preserve_default=False,
        ),
    ]
