# Generated by Django 4.2.7 on 2024-08-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0018_remove_visibility_roles_visibility_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visibility",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "superadmin"),
                    ("admin", "admin"),
                    ("manager", "manager"),
                    ("teacher", "teacher"),
                    ("student", "student"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
