# Generated by Django 4.2.7 on 2024-08-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0019_alter_visibility_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="facebook_account_link",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
