# Generated by Django 4.2.7 on 2025-04-03 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_auth",
            "0021_dataverificationrequest_user_emergency_contact_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dataverificationrequest",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_created_dvrs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
