# Generated by Django 4.2.7 on 2025-04-05 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0022_dataverificationrequest_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdataverificationrequest",
            options={"ordering": ("id",)},
        ),
        migrations.AlterUniqueTogether(
            name="userdataverificationrequest",
            unique_together={("user", "data_verification_request")},
        ),
    ]
