# Generated by Django 4.2.7 on 2025-04-05 10:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0023_alter_userdataverificationrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataverificationrequest",
            name="requested_user_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="userdataverificationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("awaiting_verification", "awaiting_verification"),
                    ("verified", "verified"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
