# Generated by Django 4.2.7 on 2025-04-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0024_dataverificationrequest_requested_user_ids_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataverificationrequest",
            name="requested_user_ids",
        ),
        migrations.AddField(
            model_name="dataverificationrequest",
            name="requested_user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("superadmin", "superadmin"),
                    ("admin", "admin"),
                    ("manager", "manager"),
                    ("teacher", "teacher"),
                    ("student", "student"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
