# Generated by Django 4.2.7 on 2025-04-05 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0025_remove_dataverificationrequest_requested_user_ids_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dataverificationrequest",
            old_name="requested_user_type",
            new_name="requested_user_types",
        ),
    ]
