# Generated by Django 4.2.7 on 2025-04-05 12:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_auth",
            "0026_rename_requested_user_type_dataverificationrequest_requested_user_types",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataverificationrequest",
            name="requested_user_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("superadmin", "superadmin"),
                        ("admin", "admin"),
                        ("manager", "manager"),
                        ("teacher", "teacher"),
                        ("student", "student"),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
