# Generated by Django 4.2.7 on 2025-04-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0027_alter_dataverificationrequest_requested_user_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataverificationrequest",
            name="name",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
