# Generated by Django 4.2.7 on 2025-04-06 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0028_alter_dataverificationrequest_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataverificationrequest",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_created_dvrs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
