# Generated by Django 4.2.7 on 2025-08-11 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0029_alter_dataverificationrequest_created_by"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PasswordResetRequest",
            new_name="VerificationCode",
        ),
    ]
