# Generated by Django 4.2.7 on 2025-08-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0030_rename_passwordresetrequest_verificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationcode",
            name="digit_code",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="source",
            field=models.CharField(
                choices=[
                    ("password_reset", "password_reset"),
                    ("email_verification", "email_verification"),
                    ("telegram_verification", "telegram_verification"),
                ],
                default="password_reset",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="verificationcode",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="token",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
