# Generated by Django 4.2.7 on 2025-08-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_auth",
            "0031_verificationcode_digit_code_verificationcode_source_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
