# Generated by Django 4.2.7 on 2025-09-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0032_user_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grace_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
