# Generated by Django 4.2.7 on 2025-10-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0033_user_grace_period_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "male"),
                    ("FEMALE", "female"),
                    ("NON_BINARY", "non_binary"),
                    ("OTHER", "other"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
