# Generated by Django 4.2.7 on 2025-11-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0034_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_log_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="contract_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="employment_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[("part_time", "part_time"), ("full_time", "full_time")],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="per_hour_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_checkin_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_checkout_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="probation_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="working_hour_per_month",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
