# Generated by Django 4.2.7 on 2026-01-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0035_user_access_log_name_user_contract_expiry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_waiting_for_activation",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="house_number",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="street",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="township",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
