# Generated by Django 4.2.7 on 2026-01-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0036_user_is_waiting_for_activation_alter_user_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_biometric_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
