# Generated by Django 4.2.7 on 2026-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0037_user_is_biometric_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_bonus_hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
