# Generated by Django 4.2.7 on 2026-02-18 01:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0039_user_course_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataverificationrequest",
            name="requested_user_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("superadmin", "superadmin"),
                        ("admin", "admin"),
                        ("manager", "manager"),
                        ("teacher", "teacher"),
                        ("finance", "finance"),
                        ("hr", "hr"),
                        ("student", "student"),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("superadmin", "superadmin"),
                        ("admin", "admin"),
                        ("manager", "manager"),
                        ("teacher", "teacher"),
                        ("finance", "finance"),
                        ("hr", "hr"),
                        ("student", "student"),
                    ],
                    max_length=128,
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visibility",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "superadmin"),
                    ("admin", "admin"),
                    ("manager", "manager"),
                    ("teacher", "teacher"),
                    ("finance", "finance"),
                    ("hr", "hr"),
                    ("student", "student"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
