# Generated by Django 4.2.7 on 2026-03-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_auth",
            "0040_alter_dataverificationrequest_requested_user_types_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
