# Generated by Django 4.2.7 on 2026-05-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0043_user_custom_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="delivery_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nrc_passport",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
