# Generated by Django 4.2.7 on 2026-05-31 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utilitas.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0051_user_phone_digits_generated_orm'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.URLField(max_length=512)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(utilitas.models.BaseModel, models.Model),
        ),
        migrations.AddConstraint(
            model_name='webpushsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'endpoint'), name='unique_user_endpoint_web_push'),
        ),
    ]
