# Generated by Django 4.2.7 on 2026-06-20

from django.db import migrations, models

import app_auth.models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0062_user_telegram_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to=app_auth.models.get_tenant_specific_upload_folder_for_id_photo,
            ),
        ),
    ]
