# Generated by Django 4.2.7 on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0063_user_id_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=8,
                null=True,
            ),
        ),
    ]
