# Generated by Django 4.2.7 on 2026-06-23 06:22

import app_auth.models
from django.db import migrations, models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0064_user_blood_type"),
    ]

    operations = [
        # Some tenants already applied a removed 0064_rename_* migration that
        # renamed this index; others still have the 0053 name. Rename only when needed.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="refreshsession",
                    new_name="app_auth_re_user_id_1fce8e_idx",
                    old_name="app_auth_re_user_id_8f3c2a_idx",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE schemaname = current_schema()
          AND indexname = 'app_auth_re_user_id_8f3c2a_idx'
    ) THEN
        ALTER INDEX app_auth_re_user_id_8f3c2a_idx
            RENAME TO app_auth_re_user_id_1fce8e_idx;
    END IF;
END $$;
""",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="id_photo_thumb",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to=app_auth.models.get_tenant_specific_upload_folder_for_id_photo,
            ),
        ),
    ]
