# Generated by Django 4.2.7 on 2026-06-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0101_user_course_oversight_scope"),
        ("app_auth", "0068_user_roles_unconstrained"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraipreferences",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="user",
            name="scoped_categories",
            field=models.ManyToManyField(
                blank=True, related_name="scoped_users", to="app_course.category"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="scoped_programs",
            field=models.ManyToManyField(
                blank=True, related_name="scoped_users", to="app_course.program"
            ),
        ),
    ]
