# Generated by Django 4.2.7 on 2026-07-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0069_user_course_oversight_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCodeCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type_digit", models.CharField(max_length=1)),
                ("year", models.PositiveSmallIntegerField()),
                ("next_sequence", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddConstraint(
            model_name="usercodecounter",
            constraint=models.UniqueConstraint(
                fields=("type_digit", "year"), name="uniq_user_code_counter_type_year"
            ),
        ),
    ]
