# Generated by Django 4.2.7 on 2026-07-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0071_user_certification"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraipreferences",
            name="monthly_usd_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Admin override: monthly USD cap. Null = org default.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
