# Generated by Django 4.2.7 on 2026-07-18 13:47

from datetime import timedelta

from django.db import migrations, models


def forwards(apps, schema_editor):
    DataVerificationRequest = apps.get_model("app_auth", "DataVerificationRequest")
    for dvr in DataVerificationRequest.objects.all().iterator():
        # Expiry: created_at + 7 days so old campaigns are already past and never banner.
        if dvr.expires_on is None and dvr.created_at is not None:
            dvr.expires_on = (dvr.created_at + timedelta(days=7)).date()
        raw = dvr.fields or []
        normalized = []
        if isinstance(raw, list):
            for item in raw:
                if isinstance(item, str):
                    normalized.append({"name": item, "required": False})
                elif isinstance(item, dict) and "name" in item:
                    normalized.append(
                        {
                            "name": item["name"],
                            "required": bool(item.get("required", False)),
                        }
                    )
        dvr.fields = normalized
        dvr.save(update_fields=["expires_on", "fields"])


def backwards(apps, schema_editor):
    DataVerificationRequest = apps.get_model("app_auth", "DataVerificationRequest")
    for dvr in DataVerificationRequest.objects.all().iterator():
        raw = dvr.fields or []
        if isinstance(raw, list):
            dvr.fields = [
                item["name"] if isinstance(item, dict) and "name" in item else item
                for item in raw
            ]
            dvr.save(update_fields=["fields"])


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0074_user_teaching_subject_polymorphic"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataverificationrequest",
            name="expires_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(forwards, backwards),
    ]
