# Generated by Django 4.2.7 on 2026-07-26 06:15

import app_auth.models
from django.db import migrations, models
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0075_dvr_expires_on_and_fields_shape"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_signature",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=schedjuice_backend.storages.PrivateMediaStorage(),
                upload_to=app_auth.models.get_tenant_specific_upload_folder_for_user_signature,
            ),
        ),
    ]
