# Generated by Django 4.2.7 on 2026-08-08 06:35

import app_auth.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        ("app_auth", "0080_user_consultation_booking_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataverificationrequest",
            name="requested_user_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("superadmin", "superadmin"),
                        ("admin", "admin"),
                        ("manager", "manager"),
                        ("teacher", "teacher"),
                        ("finance", "finance"),
                        ("hr", "hr"),
                        ("consultant", "consultant"),
                        ("student", "student"),
                    ],
                    max_length=32,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visibility",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "superadmin"),
                    ("admin", "admin"),
                    ("manager", "manager"),
                    ("teacher", "teacher"),
                    ("finance", "finance"),
                    ("hr", "hr"),
                    ("consultant", "consultant"),
                    ("student", "student"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("award_image", "Award image"),
                            ("id_image", "ID image"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=schedjuice_backend.storages.PrivateMediaStorage(),
                        upload_to=app_auth.models.get_tenant_specific_upload_folder_for_user_images,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_user_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "image_type", "-created_at"],
                        name="app_auth_us_user_id_3b4b76_idx",
                    )
                ],
            },
        ),
    ]
