# Generated by Django 4.2.7 on 2026-06-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemoProvisionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brief_slug", models.CharField(db_index=True, max_length=128)),
                ("blueprint_id", models.CharField(max_length=64)),
                ("brief_relative_path", models.CharField(max_length=256)),
                ("reset", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                (
                    "created_by_email",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
    ]
