# Generated by Django 4.2.7 on 2026-07-10 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_crm", "0003_seed_default_statuses_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="observers",
            field=models.ManyToManyField(
                blank=True, related_name="observed_leads", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="leadcomment",
            name="mentions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="leadevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("status_changed", "Status changed"),
                    ("appointment_booked", "Appointment booked"),
                    ("appointment_rescheduled", "Appointment rescheduled"),
                    ("appointment_no_show", "Appointment no-show"),
                    ("assignee_changed", "Assignee changed"),
                    ("converted", "Converted to student"),
                    ("observer_added", "Observer added"),
                ],
                max_length=32,
            ),
        ),
    ]
