# Generated by Django 4.2.7 on 2026-08-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crm', '0007_seed_default_issue_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='source',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('PARENT_COMPLAINT', 'Parent complaint')], default='INTERNAL', max_length=32),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
