# Generated by Django 4.2.7 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_crm", "0008_issue_source_and_comment_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
