# Generated by Django 4.2.7 on 2026-08-14 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_course", "0107_subject_exam_board"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "family",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("academic_excellence", "academic_excellence"),
                            ("attendance", "attendance"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("admin", "admin"),
                            ("promoted", "promoted"),
                            ("local", "local"),
                        ],
                        max_length=16,
                    ),
                ),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_award_titles",
                        to="app_course.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AwardGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_kind",
                    models.CharField(
                        choices=[("month", "month"), ("overall", "overall")],
                        max_length=16,
                    ),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="award_grants",
                        to="app_course.course",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to="app_awards.awardtitle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="award_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="awardtitle",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(
                    ("course__isnull", True), ("retired_at__isnull", True)
                ),
                name="uniq_award_title_org_name_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="awardtitle",
            constraint=models.UniqueConstraint(
                models.F("course"),
                django.db.models.functions.text.Lower("name"),
                condition=models.Q(("course__isnull", False)),
                name="uniq_award_title_local_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="awardtitle",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_pinned", False),
                    models.Q(("course__isnull", True), ("is_pinned", True)),
                    _connector="OR",
                ),
                name="award_title_pinned_org_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="awardtitle",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("family__isnull", True), ("course__isnull", True), _connector="OR"
                ),
                name="award_title_family_org_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="awardtitle",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("retired_at__isnull", True),
                    ("course__isnull", True),
                    _connector="OR",
                ),
                name="award_title_retire_org_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="awardtitle",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("course__isnull", False), ("origin", "local")),
                    models.Q(
                        ("course__isnull", True), ("origin__in", ["admin", "promoted"])
                    ),
                    _connector="OR",
                ),
                name="award_title_origin_course_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="awardgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("period_kind", "month")),
                fields=("course", "title", "user", "year", "month"),
                name="uniq_award_grant_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="awardgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("period_kind", "overall")),
                fields=("course", "title", "user"),
                name="uniq_award_grant_overall",
            ),
        ),
        migrations.AddConstraint(
            model_name="awardgrant",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("month__isnull", False),
                        ("period_kind", "month"),
                        ("year__isnull", False),
                    ),
                    models.Q(
                        ("month__isnull", True),
                        ("period_kind", "overall"),
                        ("year__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="award_grant_period_fields",
            ),
        ),
    ]
