# Generated by Django 4.2.7 on 2026-08-14 17:19

import app_awards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import schedjuice_backend.storages


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_awards", "0002_seed_award_title_manage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "background",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=schedjuice_backend.storages.PublicMediaStorage(),
                        upload_to=app_awards.models.get_upload_to_path_for_award_templates,
                    ),
                ),
                ("document", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="app_awards.awardtitle",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="awardtemplate",
            constraint=models.UniqueConstraint(
                models.F("title"),
                django.db.models.functions.text.Lower("name"),
                name="uniq_award_template_title_name",
            ),
        ),
    ]
