# Generated by Django 4.2.7 on 2024-07-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "info"),
                            ("warning", "warning"),
                            ("error", "error"),
                            ("critical", "critical"),
                        ],
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("entity_description", models.TextField(null=True)),
                ("entity", models.CharField(max_length=512, null=True)),
                ("entity_id", models.PositiveIntegerField(null=True)),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
    ]
