# Generated by Django 4.2.7 on 2024-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="category",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
