# Generated by Django 4.2.7 on 2026-04-06 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_reports", "0003_log_category_created_at_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="log",
            name="log_category_created_at_idx",
        ),
    ]
