export const RECENT_TRANSACTIONS_LIST_FIELDS = [
  "id",
  "user.id",
  "user.name",
  "course.id",
  "course.title",
  "course.start_date",
  "course.end_date",
  "transaction_id",
  "status",
  "description",
  "remarks",
  "created_by.name",
  "verified_by.name",
  "billing_start_date",
  "billing_end_date",
  "date_on_screenshot",
  "payment_method.name",
  "payment_method.payment_bank",
  "parsed_amount",
  "base_amount",
  "discount_amount",
  "invoiced_amount",
  "actual_amount",
  "discount_label",
  "issued_at",
  "payment_date",
  "covered_months",
  "group_id",
  "shared_screenshot_courses",
  "is_installment",
  "screenshot",
] as const;

export const RECENT_TRANSACTIONS_LIST_EXPAND = [
  "user",
  "course",
  "payment_method",
  "created_by",
  "verified_by",
] as const;

export const RECENT_TRANSACTIONS_PAGE_SIZE = 15;
