# Generated by Django 4.2.7 on 2026-09-13 17:36

import app_scholis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_course", "0112_usercourse_billing_cycle_anchor_date"),
        ("app_grading_reports", "0003_mark_sheets"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScholisConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("external_ref", models.CharField(max_length=200, unique=True)),
                (
                    "school_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("scholis_org_id", models.UUIDField(blank=True, null=True)),
                (
                    "api_key_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("api_key_secret_encrypted", models.TextField(blank=True, default="")),
                ("webhook_endpoint_id", models.UUIDField(blank=True, null=True)),
                (
                    "webhook_signing_secret_encrypted",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "webhook_token",
                    models.CharField(
                        default=app_scholis.models._generate_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("last_event_seq", models.BigIntegerField(blank=True, null=True)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ScholisPaperLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scholis_test_id", models.UUIDField()),
                (
                    "scholis_test_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("sections", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "column",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scholis_paper_links",
                        to="app_grading_reports.resultcolumn",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_links",
                        to="app_scholis.scholisconnection",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholis_paper_links",
                        to="app_course.course",
                    ),
                ),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scholis_paper_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ScholisLaunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scholis_test_id", models.UUIDField()),
                ("taker_ref", models.CharField(max_length=120)),
                (
                    "taker_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launches",
                        to="app_scholis.scholisconnection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scholis_launches_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="launches",
                        to="app_scholis.scholispaperlink",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholis_launches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ScholisWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.UUIDField(unique=True)),
                ("seq", models.BigIntegerField(blank=True, null=True)),
                ("type", models.CharField(max_length=120)),
                (
                    "subject_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "subject_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("from_catch_up", models.BooleanField(default=False)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="app_scholis.scholisconnection",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["connection", "seq"], name="scholis_event_conn_seq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScholisScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_id", models.UUIDField(unique=True)),
                (
                    "student_ref",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "taker_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=8)),
                ("max_score", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sections", models.JSONField(blank=True, default=list)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("synced_marks", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="app_scholis.scholispaperlink",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholis_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-released_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["link", "student"], name="scholis_score_link_student"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="scholispaperlink",
            constraint=models.UniqueConstraint(
                fields=("connection", "scholis_test_id"),
                name="scholis_paper_link_unique_test",
            ),
        ),
    ]
