# Generated by Django 4.2.7 on 2026-06-29 09:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_organization", "0065_platformopssettings_vimeo_access_token_ct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=256, unique=True)),
                ("title", models.CharField(max_length=512)),
                ("markdown_body", models.TextField(blank=True, default="")),
                (
                    "audiences",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("all", "All roles"),
                                ("admin", "Administrators"),
                                ("teacher", "Teachers"),
                                ("student", "Students"),
                            ],
                            max_length=16,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_user_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "created_by_email",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "updated_by_user_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "updated_by_email",
                    models.CharField(blank=True, default="", max_length=512),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DocCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=128, unique=True)),
                ("title", models.CharField(max_length=256)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "default_audience",
                    models.CharField(
                        choices=[
                            ("all", "All roles"),
                            ("admin", "Administrators"),
                            ("teacher", "Teachers"),
                            ("student", "Students"),
                        ],
                        default="all",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="DocVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("vimeo_id", models.CharField(blank=True, default="", max_length=64)),
                ("vimeo_uri", models.CharField(blank=True, default="", max_length=512)),
                ("duration_sec", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "uploaded_by_user_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "uploaded_by_email",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="app_product_docs.docarticle",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="docarticle",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="app_product_docs.doccategory",
            ),
        ),
        migrations.AddField(
            model_name="docarticle",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = global article (v1 only).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_organization.organization",
            ),
        ),
    ]
