from django.urls import path

from app_consultation import views

urlpatterns = [
    path(
        "consultation/public/<slug:slug>/booking-options",
        views.ConsultationPublicBookingOptionsView.as_view(),
    ),
    path(
        "consultation/public/<slug:slug>/config",
        views.ConsultationPublicConfigView.as_view(),
    ),
    path(
        "consultation/public/<slug:slug>/availability/dates",
        views.ConsultationPublicAvailabilityDatesView.as_view(),
    ),
    path(
        "consultation/public/<slug:slug>/availability",
        views.ConsultationPublicAvailabilityView.as_view(),
    ),
    path(
        "consultation/public/<slug:slug>/bookings",
        views.ConsultationPublicBookingCreateView.as_view(),
    ),
    path(
        "consultation/public/bookings/by-token",
        views.ConsultationPublicBookingByTokenView.as_view(),
    ),
    path(
        "consultation/public/cancel",
        views.ConsultationPublicCancelView.as_view(),
    ),
    path(
        "consultation/me/booking-link",
        views.ConsultationMeBookingLinkView.as_view(),
    ),
    path(
        "consultation/me/booking-link/rotate",
        views.ConsultationMeBookingLinkRotateView.as_view(),
    ),
    path(
        "consultation/me/whitelist",
        views.ConsultationMeWhitelistView.as_view(),
    ),
    path(
        "consultation/me/whitelist/apply-preset",
        views.ConsultationMeWhitelistApplyPresetView.as_view(),
    ),
    path(
        "consultation/me/bookings",
        views.ConsultationMeBookingsView.as_view(),
    ),
    path(
        "consultation/bookings/<int:booking_id>/approve",
        views.ConsultationBookingApproveView.as_view(),
    ),
    path(
        "consultation/bookings/<int:booking_id>/cancel",
        views.ConsultationBookingCancelView.as_view(),
    ),
    path(
        "consultation/bookings/<int:booking_id>/manage-link",
        views.ConsultationBookingManageLinkView.as_view(),
    ),
]
