# Generated by Django 4.2.7 on 2026-06-16 18:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShadowDenial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_name", models.CharField(max_length=128)),
                ("view_name", models.CharField(max_length=256)),
                ("path_pattern", models.CharField(max_length=256)),
                ("method", models.CharField(max_length=8)),
                (
                    "missing_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128), size=None
                    ),
                ),
                ("role_signature", models.CharField(max_length=256)),
                ("legacy_allowed", models.BooleanField(default=True)),
                ("hit_count", models.PositiveIntegerField(default=1)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("sample", models.JSONField(default=dict)),
            ],
            options={
                "unique_together": {
                    (
                        "schema_name",
                        "view_name",
                        "method",
                        "role_signature",
                        "missing_codes",
                    )
                },
            },
        ),
    ]
