# Generated by Django 4.2.7 on 2026-04-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_custom_fields", "0002_customfielddefinition_ui_surfaces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfielddefinition",
            name="form_input_mode",
            field=models.CharField(
                choices=[("editable", "editable"), ("read_only", "read_only")],
                default="editable",
                help_text="When the field appears on a form, whether it is editable or read-only.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="customfielddefinition",
            name="show_on_create",
            field=models.BooleanField(
                default=True,
                help_text="Show on create forms (subject to form_input_mode when on form).",
            ),
        ),
        migrations.AlterField(
            model_name="customfielddefinition",
            name="show_on_detail",
            field=models.BooleanField(
                default=True, help_text="Show on read-only detail views."
            ),
        ),
        migrations.AlterField(
            model_name="customfielddefinition",
            name="show_on_edit",
            field=models.BooleanField(
                default=True,
                help_text="Show on edit forms (subject to form_input_mode when on form).",
            ),
        ),
    ]
