# Generated by Django 4.2.7 on 2026-07-30 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_attachment", "0025_attachment_welcome_board"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_custom_fields", "0008_uniq_active_field_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fielddefinition",
            name="field_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("text", "text"),
                    ("textarea", "textarea"),
                    ("number", "number"),
                    ("date", "date"),
                    ("datetime", "datetime"),
                    ("boolean", "boolean"),
                    ("choice", "choice"),
                    ("multichoice", "multichoice"),
                    ("email", "email"),
                    ("url", "url"),
                    ("attachment", "attachment"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="CustomFieldAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(db_index=True, max_length=128)),
                ("field_key", models.SlugField(max_length=100)),
                (
                    "attachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_link",
                        to="app_attachment.attachment",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_custom_fields_customfieldattachment",
            },
        ),
    ]
