# Generated by Django 4.2.7 on 2026-06-21 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("color", models.CharField(default="#64748b", max_length=16)),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("STAFF", "Staff"),
                            ("BOTH", "Both"),
                        ],
                        default="BOTH",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReportTypeField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_key", models.SlugField(max_length=100)),
                ("field_label", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "text"),
                            ("textarea", "textarea"),
                            ("number", "number"),
                            ("date", "date"),
                            ("datetime", "datetime"),
                            ("boolean", "boolean"),
                            ("choice", "choice"),
                            ("multichoice", "multichoice"),
                            ("email", "email"),
                            ("url", "url"),
                            ("staff_user_fk", "staff user"),
                            ("course_fk", "course"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("choices", models.JSONField(blank=True, null=True)),
                ("validation_rules", models.JSONField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "report_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="app_userlog.reporttype",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="reporttypefield",
            constraint=models.UniqueConstraint(
                fields=("report_type", "field_key"),
                name="uniq_reporttypefield_type_key",
            ),
        ),
    ]
