# Generated by Django 4.2.7 on 2026-06-29 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_telegram", "0003_aidisambiguationpending"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramlinktoken",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="telegrampendinggrouplink",
            options={"ordering": ["id"]},
        ),
    ]
