# Generated by Django 4.2.7 on 2026-08-09 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_telegram", "0006_telegramloginsession"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramloginsession",
            options={"ordering": ["id"]},
        ),
    ]
