# Generated by Django 4.2.7 on 2026-08-17 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_certificates", "0002_certificatetemplatecategory_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="CertificateTemplate"),
                migrations.DeleteModel(name="CertificateTemplateCategory"),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS app_certificates_certificatetemplate CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS app_certificates_certificatetemplatecategory CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
