# Generated by Django 4.2.7 on 2023-12-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_success",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="response",
            field=models.TextField(default="empty"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
