# Generated by Django 4.2.7 on 2023-12-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tasks", "0002_task_is_success_task_response_task_retry_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                choices=[
                    ("remove_ms_member", "remove_ms_member"),
                    ("delete_user", "delete_user"),
                    ("delete_course", "delete_course"),
                ],
                max_length=512,
            ),
        ),
    ]
