# Generated by Django 4.2.7 on 2023-12-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tasks", "0003_alter_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="So that another worker cannot take while this task is being processed by the current worker.",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="status_code",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
