# Generated by Django 4.2.7 on 2024-02-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tasks", "0004_task_is_locked_task_status_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                choices=[
                    ("remove_ms_member", "remove_ms_member"),
                    ("delete_user", "delete_user"),
                    ("delete_course", "delete_course"),
                    ("clean_up_quiz_files", "clean_up_quiz_files"),
                ],
                max_length=512,
            ),
        ),
    ]
