# Generated by Django 4.2.7 on 2026-03-15 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_tasks", "0011_croncommandlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="croncommandlog",
            options={"ordering": ["id"]},
        ),
    ]
