# Generated by Django 4.2.7 on 2026-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_tasks", "0012_alter_croncommandlog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                choices=[
                    ("remove_ms_member", "remove_ms_member"),
                    ("delete_user", "delete_user"),
                    ("delete_course", "delete_course"),
                    ("leave_telegram_group", "leave_telegram_group"),
                    ("clean_up_quiz_files", "clean_up_quiz_files"),
                    ("delete_quiz_files", "delete_quiz_files"),
                    ("send_email", "send_email"),
                    ("create_ms_user", "create_ms_user"),
                    ("send_custom_email", "send_custom_email"),
                    ("create_dvr_and_send_email", "create_dvr_and_send_email"),
                ],
                max_length=512,
            ),
        ),
    ]
