# Generated by Django 4.2.7 on 2023-11-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0003_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="microsoft_channel_id",
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="microsoft_group_id",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
