# Generated by Django 4.2.7 on 2023-12-02 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0004_course_microsoft_channel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="available_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
