# Generated by Django 4.2.7 on 2023-12-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0005_assignment_available_date_assignment_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="available_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(),
        ),
    ]
