# Generated by Django 4.2.7 on 2023-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0006_alter_assignment_available_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="reference_key",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
