# Generated by Django 4.2.7 on 2023-12-21 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0007_assignment_reference_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="reference_key",
        ),
    ]
