# Generated by Django 4.2.7 on 2024-01-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0008_remove_assignment_reference_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=1024, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="app_course.category",
            ),
            preserve_default=False,
        ),
    ]
