# Generated by Django 4.2.7 on 2024-02-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0011_assignment_available_score_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="max_attempts",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
