# Generated by Django 4.2.7 on 2024-02-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0012_assignment_max_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
