# Generated by Django 4.2.7 on 2024-02-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0013_submission_attempt_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="attempt_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
