# Generated by Django 4.2.7 on 2024-02-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0015_assignment_results_release_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignedAsRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512, unique=True)),
                (
                    "is_collision_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="If disabled, event collision calculation will be ignored.",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="usercourse",
            name="assigned_as_role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app_course.assignedasrole",
            ),
        ),
    ]
