# Generated by Django 4.2.7 on 2024-07-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0016_assignedasrole_usercourse_assigned_as_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=512, null=True, unique=True),
        ),
    ]
