# Generated by Django 4.2.7 on 2024-07-31 18:07

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_course", "0017_course_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "planned"),
                    ("active", "active"),
                    ("ended", "ended"),
                ],
                default="planned",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="CourseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 7, 31, 18, 7, 35, 800395, tzinfo=datetime.timezone.utc
                        ),
                        help_text="Editable created date",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "course_code",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "student_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("course_start_date", models.DateField(blank=True, null=True)),
                ("course_end_date", models.DateField(blank=True, null=True)),
                ("is_manually_created", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_histories",
                        to="app_course.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
    ]
