# Generated by Django 4.2.7 on 2024-07-31 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0018_course_status_coursehistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursehistory",
            name="action_date",
        ),
        migrations.AddField(
            model_name="coursehistory",
            name="assigned_as",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app_course.assignedasrole",
            ),
        ),
    ]
