# Generated by Django 4.2.7 on 2024-07-31 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0019_remove_coursehistory_action_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursehistory",
            old_name="student_email",
            new_name="user_email",
        ),
        migrations.RenameField(
            model_name="coursehistory",
            old_name="student_name",
            new_name="user_name",
        ),
    ]
