# Generated by Django 4.2.7 on 2024-07-31 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_course", "0020_rename_student_email_coursehistory_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursehistory",
            name="course_code",
        ),
        migrations.RemoveField(
            model_name="coursehistory",
            name="course_end_date",
        ),
        migrations.RemoveField(
            model_name="coursehistory",
            name="course_name",
        ),
        migrations.RemoveField(
            model_name="coursehistory",
            name="course_start_date",
        ),
        migrations.RemoveField(
            model_name="coursehistory",
            name="is_manually_created",
        ),
        migrations.RemoveField(
            model_name="coursehistory",
            name="user_email",
        ),
        migrations.RemoveField(
            model_name="coursehistory",
            name="user_name",
        ),
        migrations.AddField(
            model_name="coursehistory",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_histories_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
