# Generated by Django 4.2.7 on 2024-07-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0021_remove_coursehistory_course_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursehistory",
            name="completion_type",
            field=models.CharField(
                choices=[
                    ("completed", "completed"),
                    ("dropped", "dropped"),
                    ("failed", "failed"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
