# Generated by Django 4.2.7 on 2024-07-31 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0002_paymentplan_remove_paymentterm_payment_and_more"),
        ("app_course", "0022_coursehistory_completion_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="payment_plan",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="app_finance.paymentplan",
            ),
        ),
    ]
