# Generated by Django 4.2.7 on 2024-08-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0023_course_payment_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="batch_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
