# Generated by Django 4.2.7 on 2024-08-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0024_course_batch_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
