# Generated by Django 4.2.7 on 2024-08-10 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0025_alter_course_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="payment_plan",
        ),
    ]
