# Generated by Django 4.2.7 on 2024-08-14 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0026_remove_course_payment_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="instructions",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="description",
        ),
    ]
