# Generated by Django 4.2.7 on 2024-08-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0027_remove_assignment_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="instructions",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="description",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
