# Generated by Django 4.2.7 on 2024-08-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0029_dailynote"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="default_daily_note",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
