# Generated by Django 4.2.7 on 2025-04-17 20:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0030_course_default_daily_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_close_on_sabbath",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="repeat_every",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=512),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
