# Generated by Django 4.2.7 on 2025-05-17 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0031_course_is_close_on_sabbath_course_is_recurring_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="available_date",
            new_name="available_datetime",
        ),
        migrations.RenameField(
            model_name="assignment",
            old_name="due_date",
            new_name="due_datetime",
        ),
    ]
