# Generated by Django 4.2.7 on 2025-05-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_course",
            "0032_rename_available_date_assignment_available_datetime_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_graded",
            field=models.BooleanField(default=False),
        ),
    ]
