# Generated by Django 4.2.7 on 2025-09-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0034_campus_course_campus"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_join_code_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="course",
            name="join_code",
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
