# Generated by Django 4.2.7 on 2025-09-01 15:42

import app_course.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0035_course_is_join_code_enabled_course_join_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="join_code",
            field=models.CharField(
                blank=True,
                default=app_course.models.generate_join_code,
                max_length=512,
                null=True,
                unique=True,
            ),
        ),
    ]
