# Generated by Django 4.2.7 on 2025-09-13 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0036_alter_course_join_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="join_code_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
