# Generated by Django 4.2.7 on 2025-09-13 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0037_course_join_code_created"),
        ("app_course", "0037_coursejoinrequest"),
    ]

    operations = []
