# Generated by Django 4.2.7 on 2025-09-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0038_merge_20250913_0943"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursejoinrequest",
            name="reject_reason",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="coursejoinrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
