# Generated by Django 4.2.7 on 2025-10-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0039_coursejoinrequest_reject_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="meeting_link",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
