# Generated by Django 4.2.7 on 2025-10-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0040_course_meeting_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="batch_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
