# Generated by Django 4.2.7 on 2025-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0043_course_is_payment_enabled_course_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
