# Generated by Django 4.2.7 on 2025-12-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_finance", "0036_paymentplan"),
        ("app_course", "0044_alter_event_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="price",
        ),
        migrations.RemoveField(
            model_name="course",
            name="price_currency",
        ),
        migrations.AddField(
            model_name="course",
            name="payment_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app_finance.paymentplan",
            ),
        ),
    ]
