# Generated by Django 4.2.7 on 2025-12-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_course",
            "0045_remove_course_price_remove_course_price_currency_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="student_count",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="teacher_count",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "planned"),
                    ("active", "active"),
                    ("ended", "ended"),
                    ("paused", "paused"),
                ],
                default="planned",
                max_length=16,
            ),
        ),
    ]
