# Generated by Django 4.2.7 on 2026-01-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0046_course_student_count_course_teacher_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="join_code_created",
        ),
        migrations.AddField(
            model_name="course",
            name="join_code_expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
