# Generated by Django 4.2.7 on 2026-01-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0047_remove_course_join_code_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="is_dropped_out",
            field=models.BooleanField(default=False),
        ),
    ]
