# Generated by Django 4.2.7 on 2026-01-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0048_usercourse_is_dropped_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="dropped_out_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
