# Generated by Django 4.2.7 on 2026-01-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0049_usercourse_dropped_out_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedasrole",
            name="seniority",
            field=models.CharField(
                choices=[
                    ("MAIN_TEACHER", "MAIN_TEACHER"),
                    ("ASSISTANT_TEACHER", "ASSISTANT_TEACHER"),
                    ("OTHER", "OTHER"),
                ],
                default="OTHER",
                max_length=100,
                null=True,
            ),
        ),
    ]
