# Generated by Django 4.2.7 on 2026-01-19 04:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0050_assignedasrole_seniority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="teacher_count",
            new_name="main_teacher_count",
        ),
    ]
