# Generated by Django 4.2.7 on 2026-01-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0051_rename_teacher_count_course_main_teacher_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="assistant_teacher_count",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
