# Generated by Django 4.2.7 on 2026-01-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0052_course_assistant_teacher_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[("WD", "WD"), ("WE", "WE"), ("OTHER", "OTHER")],
                max_length=16,
                null=True,
            ),
        ),
    ]
