# Generated by Django 4.2.7 on 2026-01-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0053_course_course_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="is_fully_paid",
            field=models.BooleanField(default=False),
        ),
    ]
