# Generated by Django 4.2.7 on 2026-02-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0054_usercourse_is_fully_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
