# Generated by Django 4.2.7 on 2026-02-13 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0055_submission_feedback"),
        ("app_course", "0056_userattendance_hourly_rate_at_creation"),
    ]

    operations = []
