# Generated by Django 4.2.7 on 2026-03-13 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_course", "0067_subject_course_exam_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="processedteamsrecording",
            name="meeting_id",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="processedteamsrecording",
            name="recording_content_url",
            field=models.CharField(
                blank=True,
                help_text="Graph API URL to stream content (requires auth). Not a shareable link.",
                max_length=2048,
            ),
        ),
        migrations.CreateModel(
            name="UserUploadedRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_date",
                    models.DateField(help_text="The date when the class was recorded."),
                ),
                ("description", models.CharField(blank=True, max_length=1024)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_recordings",
                        to="app_course.course",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["course", "recorded_date", "created_at"],
            },
        ),
    ]
