# Generated by Django 4.2.7 on 2026-04-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0074_backfill_zoom_user_id_remove_from_userattendance"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AlterField(
            model_name="processedvideoattendancereport",
            name="platform",
            field=models.CharField(
                choices=[("microsoft_teams", "Microsoft Teams"), ("zoom", "Zoom")],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="userattendance",
            name="source",
            field=models.CharField(
                choices=[("microsoft_teams", "Microsoft Teams"), ("zoom", "Zoom")],
                db_index=True,
                default="microsoft_teams",
                max_length=32,
            ),
        ),
    ]
