# Generated by Django 4.2.7 on 2026-04-26 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0076_course_custom_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
    ]
