# Generated by Django 4.2.7 on 2026-05-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0077_alter_course_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="zoom_account_id",
            field=models.CharField(
                blank=True,
                help_text="External Zoom account_id of the connected ZoomAccount for OAuth and reports.",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="zoom_meeting_host_id",
            field=models.CharField(
                blank=True,
                help_text="Zoom user_id of the meeting host when known.",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="zoom_meeting_uuid",
            field=models.CharField(
                blank=True,
                help_text="Zoom meeting UUID (Reports API / refresh-from-Zoom).",
                max_length=512,
                null=True,
            ),
        ),
    ]
