# Generated by Django 4.2.7 on 2026-05-22 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0080_teacher_course_reminder"),
        ("app_course", "0091_repair_course_search_state"),
    ]

    operations = []
