# Generated by Django 4.2.7 on 2026-05-23 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0092_merge_20260523_0102"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="teachercoursereminder",
            new_name="app_course__reminde_b92567_idx",
            old_name="app_course_te_reminder_8368e9_idx",
        ),
    ]
