# Generated by Django 4.2.7 on 2026-06-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0097_remove_usercourse_is_fully_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="geofence_radius_meters",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="campus",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="campus",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
