# Generated by Django 4.2.7 on 2026-06-28 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0100_category_search_text_and_vector"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
    ]
