# Generated by Django 4.2.7 on 2026-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0104_course_id_card_expiry_date"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="coursemembershipevent",
            new_name="app_course__course__82fb30_idx",
            old_name="app_course__course__6a8f2d_idx",
        ),
        migrations.RenameIndex(
            model_name="coursemembershipevent",
            new_name="app_course__course__5cce45_idx",
            old_name="app_course__course__9c4e1a_idx",
        ),
        migrations.AddField(
            model_name="assignedasrole",
            name="is_substitute",
            field=models.BooleanField(
                default=False,
                help_text="Substitute roles cover specific session dates only and can auto-expire. Requires Main Teacher or Assistant Teacher seniority.",
            ),
        ),
    ]
