# Generated by Django 4.2.7 on 2026-07-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0105_assignedasrole_is_substitute"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="substitute_auto_remove_on",
            field=models.DateField(
                blank=True,
                help_text="Local date of the last covered session for a substitute assignment. The remove-expired-substitutes cron removes this row the day after.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="coursemembershipevent",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("api", "api"),
                    ("web_ai", "web_ai"),
                    ("telegram_bot", "telegram_bot"),
                    ("import", "import"),
                    ("cron", "cron"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
