# Generated by Django 4.2.7 on 2026-08-18 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_course", "0107_subject_exam_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="max_sessions",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Session-credit cap. Null on weekly programs.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(365)],
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="default_max_sessions",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Default max sessions seeded onto new session-credit courses.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="is_session_credit_scheduling",
            field=models.BooleanField(
                default=False,
                help_text="When true, courses in this program use click-calendar session-credit scheduling.",
            ),
        ),
    ]
