#!/usr/bin/env python3
"""Merge per-slice hygiene YAML reports into ambiguous + deleted markdown."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


def load_reports(directory: Path) -> list[dict]:
    reports = []
    for path in sorted(directory.glob("*.yaml")):
        data = yaml.safe_load(path.read_text()) or {}
        data["_report_file"] = str(path)
        reports.append(data)
    return reports


def _rows_from(reports: list[dict], key: str) -> list[dict]:
    rows: list[dict] = []
    seen: set[tuple[str, str, str, str]] = set()
    for report in reports:
        repo = report.get("repo", "")
        slice_id = report.get("slice_id", "")
        for item in report.get(key) or []:
            path = item.get("path", "")
            symbol = item.get("symbol", "") or item.get("test_name", "")
            reason = item.get("reason", "")
            dedupe = (repo, path, symbol, reason)
            if dedupe in seen:
                continue
            seen.add(dedupe)
            rows.append(
                {
                    "repo": repo,
                    "slice_id": slice_id,
                    "path": path,
                    "symbol": symbol,
                    "reason": reason,
                    "notes": item.get("notes", ""),
                    "kind": key,
                }
            )
    rows.sort(key=lambda r: (r["repo"], r["path"], r["symbol"]))
    return rows


def to_ambiguous_md(rows: list[dict], cleanup_date: str) -> str:
    lines = [
        f"# Hygiene — ambiguous candidates ({cleanup_date})",
        "",
        "Review before any further deletes. Generated by `merge_hygiene_reports.py`.",
        "",
        "| repo | slice_id | path | symbol | reason | notes |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        notes = (r.get("notes") or "").replace("|", "\\|").replace("\n", " ")
        sym = (r.get("symbol") or "").replace("|", "\\|")
        lines.append(
            f"| {r['repo']} | {r['slice_id']} | {r['path']} | `{sym}` | {r['reason']} | {notes} |"
        )
    lines.append("")
    return "\n".join(lines)


def to_deleted_md(deleted: list[dict], fixed_docs: list[dict], antifixes: list[dict], cleanup_date: str) -> str:
    lines = [
        f"# Hygiene — deleted / fixed (obvious) ({cleanup_date})",
        "",
        "## Deleted dead code",
        "",
        "| repo | slice_id | path | symbol | reason |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in deleted:
        sym = (r.get("symbol") or "").replace("|", "\\|")
        lines.append(
            f"| {r['repo']} | {r['slice_id']} | {r['path']} | `{sym}` | {r['reason']} |"
        )
    lines.extend(
        [
            "",
            "## Fixed docs/comments",
            "",
            "| repo | slice_id | path | reason |",
            "| --- | --- | --- | --- |",
        ]
    )
    for r in fixed_docs:
        lines.append(
            f"| {r['repo']} | {r['slice_id']} | {r['path']} | {r['reason']} |"
        )
    lines.extend(
        [
            "",
            "## Anti-pattern fixes",
            "",
            "| repo | slice_id | path | reason | notes |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for r in antifixes:
        notes = (r.get("notes") or "").replace("|", "\\|").replace("\n", " ")
        lines.append(
            f"| {r['repo']} | {r['slice_id']} | {r['path']} | {r['reason']} | {notes} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reports-dir", type=Path, required=True)
    parser.add_argument("--cleanup-date", required=True)
    parser.add_argument("--out-ambiguous", type=Path, required=True)
    parser.add_argument("--out-deleted", type=Path, required=True)
    args = parser.parse_args()

    reports = load_reports(args.reports_dir)
    if not reports:
        print(f"No YAML reports in {args.reports_dir}", file=sys.stderr)
        return 1

    args.out_ambiguous.write_text(
        to_ambiguous_md(_rows_from(reports, "ambiguous"), args.cleanup_date)
    )
    args.out_deleted.write_text(
        to_deleted_md(
            _rows_from(reports, "deleted"),
            _rows_from(reports, "fixed_docs"),
            _rows_from(reports, "anti_pattern_fixes"),
            args.cleanup_date,
        )
    )
    print(f"Wrote {args.out_ambiguous}")
    print(f"Wrote {args.out_deleted}")
    print(f"Reports merged: {len(reports)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
