#!/usr/bin/env python3
"""Merge per-slice cleanup YAML reports into one ambiguous markdown list."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


def load_reports(directory: Path) -> list[dict]:
    reports = []
    for path in sorted(directory.glob("*.yaml")):
        data = yaml.safe_load(path.read_text()) or {}
        data["_report_file"] = str(path)
        reports.append(data)
    return reports


def merge_ambiguous(reports: list[dict]) -> list[dict]:
    seen: set[tuple[str, str, str]] = set()
    rows: list[dict] = []
    for report in reports:
        repo = report.get("repo", "")
        for item in report.get("ambiguous") or []:
            key = (repo, item.get("path", ""), item.get("test_name", ""))
            if key in seen:
                continue
            seen.add(key)
            rows.append(
                {
                    "repo": repo,
                    "slice_id": report.get("slice_id", ""),
                    "path": item.get("path", ""),
                    "test_name": item.get("test_name", ""),
                    "reason": item.get("reason", ""),
                    "notes": item.get("notes", ""),
                }
            )
    rows.sort(key=lambda r: (r["repo"], r["path"], r["test_name"]))
    return rows


def merge_deleted(reports: list[dict]) -> list[dict]:
    rows: list[dict] = []
    for report in reports:
        repo = report.get("repo", "")
        for item in report.get("deleted") or []:
            rows.append(
                {
                    "repo": repo,
                    "slice_id": report.get("slice_id", ""),
                    "path": item.get("path", ""),
                    "test_name": item.get("test_name", ""),
                    "reason": item.get("reason", ""),
                }
            )
    rows.sort(key=lambda r: (r["repo"], r["path"], r["test_name"]))
    return rows


def to_ambiguous_md(rows: list[dict], cleanup_date: str) -> str:
    lines = [
        f"# Test cleanup — ambiguous candidates ({cleanup_date})",
        "",
        "Review before any further deletes. Generated by `merge_test_cleanup_reports.py`.",
        "",
        "| repo | slice_id | path | test_name | reason | notes |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        notes = (r.get("notes") or "").replace("|", "\\|").replace("\n", " ")
        lines.append(
            f"| {r['repo']} | {r['slice_id']} | {r['path']} | `{r['test_name']}` | {r['reason']} | {notes} |"
        )
    lines.append("")
    return "\n".join(lines)


def to_deleted_md(rows: list[dict], cleanup_date: str) -> str:
    lines = [
        f"# Test cleanup — deleted (obvious) ({cleanup_date})",
        "",
        "| repo | slice_id | path | test_name | reason |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        lines.append(
            f"| {r['repo']} | {r['slice_id']} | {r['path']} | `{r['test_name']}` | {r['reason']} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--reports-dir",
        type=Path,
        required=True,
        help="Directory of per-slice YAML reports",
    )
    parser.add_argument("--cleanup-date", required=True, help="YYYY-MM-DD")
    parser.add_argument(
        "--out-ambiguous",
        type=Path,
        required=True,
        help="Output markdown for ambiguous list",
    )
    parser.add_argument(
        "--out-deleted",
        type=Path,
        required=True,
        help="Output markdown for deleted rollup",
    )
    args = parser.parse_args()

    reports = load_reports(args.reports_dir)
    if not reports:
        print(f"No YAML reports in {args.reports_dir}", file=sys.stderr)
        return 1

    args.out_ambiguous.write_text(
        to_ambiguous_md(merge_ambiguous(reports), args.cleanup_date)
    )
    args.out_deleted.write_text(
        to_deleted_md(merge_deleted(reports), args.cleanup_date)
    )
    print(f"Wrote {args.out_ambiguous}")
    print(f"Wrote {args.out_deleted}")
    print(f"Reports merged: {len(reports)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
