"""
Django settings for schedjuice project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import datetime
import logging
import os
import sys
from pathlib import Path

import dj_database_url
from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured
from tenant_schemas.middleware import DefaultTenantMiddleware
from corsheaders.defaults import default_headers
from urllib.parse import urlparse


class MyDefaultTenantMiddleware(DefaultTenantMiddleware):
    DEFAULT_SCHEMA_NAME = "default"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET", cast=str)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

# django-silk: SQL/request profiling for JSON APIs (see CLAUDE.md). Requires DEBUG=True and SILKY_ENABLED=true.
SILK_ENABLED = DEBUG and config("SILKY_ENABLED", default=False, cast=bool)

# nplusone: lazy-load N+1 detection (dev/test only). Requires DEBUG=True and NPLUSONE_ENABLED=true.
NPLUSONE_ENABLED = DEBUG and config("NPLUSONE_ENABLED", default=False, cast=bool)
POSTHOG_ENABLED = config("POSTHOG_ENABLED", default=False, cast=bool)
POSTHOG_HOST = config("POSTHOG_HOST", default="")
POSTHOG_API_KEY = config("POSTHOG_API_KEY", default="")
POSTHOG_API_SAMPLE_RATE = config("POSTHOG_API_SAMPLE_RATE", default=0.5, cast=float)
POSTHOG_ENVIRONMENT = config("POSTHOG_ENVIRONMENT", default="development")

ALLOWED_HOSTS = ["*"]

# Application definition

SHARED_APPS = (
    "tenant_schemas",
    "corsheaders",
    "app_organization",
    "app_zoom",
    "app_rbac_audit",
    "app_demo",
    "app_ai",
    "app_product_docs",
    "django_q",
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "rest_framework",
    "storages",
    "debug_toolbar",
    # Public-schema only (never duplicate into tenant schemas). Must be unconditional so
    # migrate_schemas --shared creates tables even when SILKY_ENABLED is false.
    "silk",
)
TENANT_APPS = (
    "django.contrib.contenttypes",
    "django.contrib.admin",
    # DB-backed sessions per tenant (admin login, Silk). REST API uses JWT; this does not affect DRF.
    "django.contrib.sessions",
    "django.contrib.staticfiles",
    "corsheaders",
    "app_custom_fields",
    "app_auth",
    "app_course",
    "app_awards",
    "app_documents",
    "app_data",
    "app_attendance",
    "app_quiz_v3",
    "app_welcome_board",
    "app_utility_notifications",
    "app_attachment",
    "app_microsoft",
    "app_telegram",
    "app_google",
    "app_announcement",
    "app_tasks",
    "app_utils",
    "app_reports",
    "app_department",
    "app_crm",
    "app_consultation",
    "app_userlog",
    "app_points",
    "app_grading_reports",
    "app_finance",
    "app_wiki",
    "app_tools",
    "app_library",
    "app_hr",
    "app_admissions",
    "app_certificates",
    "app_chat",
    "app_rbac",
    "expo_notifications",
    "rest_framework",
    "storages",
    "drf_chunked_upload",
    "debug_toolbar",
    "djmoney",
)

INSTALLED_APPS = [
    # Before daphne: custom `runserver` (relaxed WebSocket handshake / close timeouts for dev).
    "schedjuice_backend.apps.SchedjuiceBackendConfig",
    "daphne",
    "tenant_schemas",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # CORS
    "corsheaders",
    # q
    "django_q",
    # local apps
    "app_organization",
    "app_zoom",
    "app_custom_fields",
    "app_auth",
    "app_course",
    "app_awards",
    "app_documents",
    "app_data",
    "app_attendance",
    "app_quiz_v3",
    "app_welcome_board",
    "app_utility_notifications",
    "app_attachment",
    "app_microsoft",
    "app_telegram",
    "app_google",
    "app_announcement",
    "app_tasks",
    "expo_notifications",  # Before app_utils so app_utils can override DeviceAdmin
    "app_utils",
    "app_reports",
    "app_department",
    "app_crm",
    "app_consultation",
    "app_userlog",
    "app_points",
    "app_grading_reports",
    "app_finance",
    "app_wiki",
    "app_tools",
    "app_library",
    "app_ws",
    "app_hr",
    "app_admissions",
    "app_certificates",
    "app_chat",
    "app_rbac",
    "app_rbac_audit",
    "app_demo",
    "app_ai",
    "app_product_docs",
    "utilitas.traffic_analytics.apps.TrafficAnalyticsConfig",
    # third-party apps
    "rest_framework",
    "rest_framework_swagger",
    "drf_chunked_upload",
    "drf_yasg",
    "debug_toolbar",
    "django_extensions",
    "storages",
    "djmoney",
    "silk",
    # add this at last
    "django_cleanup.apps.CleanupConfig",
]

MIDDLEWARE = [
    "app_organization.middlewares.XHeaderTenantMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
if SILK_ENABLED:
    MIDDLEWARE.append("silk.middleware.SilkyMiddleware")
if NPLUSONE_ENABLED:
    INSTALLED_APPS.append("nplusone.ext.django")
    MIDDLEWARE.insert(0, "nplusone.ext.django.NPlusOneMiddleware")
    MIDDLEWARE.insert(1, "utilitas.middlewares.NPlusOneContextMiddleware")
if DEBUG:
    MIDDLEWARE.extend(
        [
            "debug_toolbar.middleware.DebugToolbarMiddleware",
            "utilitas.middlewares.QueryLoggerMiddleware",
        ]
    )
else:
    # debug_toolbar's middleware does per-request work even when the panel
    # never renders; QueryLoggerMiddleware is a no-op without DEBUG.
    # tenant_schemas' system check requires SHARED_APPS/TENANT_APPS to stay
    # subsets of INSTALLED_APPS, so strip debug_toolbar from all three.
    INSTALLED_APPS.remove("debug_toolbar")
    SHARED_APPS = tuple(a for a in SHARED_APPS if a != "debug_toolbar")
    TENANT_APPS = tuple(a for a in TENANT_APPS if a != "debug_toolbar")
if POSTHOG_ENABLED:
    MIDDLEWARE.append("utilitas.traffic_analytics.middleware.TrafficAnalyticsMiddleware")

if NPLUSONE_ENABLED:
    NPLUSONE_LOG_DIR = Path(
        config("NPLUSONE_LOG_DIR", default=str(BASE_DIR / "logs" / "nplusone"))
    )
    NPLUSONE_LOGGER = logging.getLogger("nplusone")
    NPLUSONE_LOG_LEVEL = logging.WARN
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
            },
            "nplusone_jsonl": {
                "()": "utilitas.nplusone_logging.NPlusOneJsonlHandler",
                "log_dir": str(NPLUSONE_LOG_DIR),
            },
        },
        "loggers": {
            "nplusone": {
                "handlers": ["console", "nplusone_jsonl"],
                "level": "WARN",
            },
        },
    }

LOCAL_TEST_DATABASE_URL = "postgres://user:password@127.0.0.1:55432/db"
LOCAL_TEST_DATABASE_HOSTS = frozenset({"127.0.0.1", "localhost", "::1"})


def _resolve_database_url() -> str:
    if "test" in sys.argv:
        return os.environ.get("DATABASE_URL", LOCAL_TEST_DATABASE_URL)
    return config("DATABASE_URL")


def _assert_local_test_database(database_url: str) -> None:
    if "test" not in sys.argv:
        return
    host = urlparse(database_url).hostname or ""
    if host not in LOCAL_TEST_DATABASE_HOSTS:
        raise ImproperlyConfigured(
            "Backend tests must use the local Docker Postgres database, not Railway or "
            "other remote hosts. Start the test DB and run tests via "
            "scripts/run_backend_tests.sh, or set "
            f"DATABASE_URL={LOCAL_TEST_DATABASE_URL}"
        )


if "test" in sys.argv:
    # Log N+1 issues during tests but do not fail unrelated suites; opt in via env.
    NPLUSONE_RAISE = config("NPLUSONE_RAISE", default=False, cast=bool)
    TEST_RUNNER = "schedjuice_backend.test_runner.SchedjuiceTestRunner"

TENANT_LIMIT_SET_CALLS = True
PUBLIC_SCHEMA_NAME = "public"

ROOT_URLCONF = "schedjuice_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "schedjuice_backend.asgi.application"

CHAT_AND_WEBSOCKET_ENABLED = config(
    "CHAT_AND_WEBSOCKET_ENABLED", default=False, cast=bool
)

# Use 127.0.0.1 in REDIS_URL on Windows + WSL: "localhost" may resolve to ::1 while
# Redis listens on IPv4 only, breaking channels_redis during WebSocket connect.


def _redis_url_with_db(db: int) -> str:
    """One Redis instance, but a distinct logical DB per role (channels /0,
    cache /1, celery broker /2, celery results /3, django-q2 /4) so cache
    operations can never touch broker data and per-role memory stays
    observable via INFO keyspace."""
    from urllib.parse import urlsplit, urlunsplit

    base = config("REDIS_URL", default="redis://127.0.0.1:6379")
    return urlunsplit(urlsplit(base)._replace(path=f"/{db}"))


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [_redis_url_with_db(0)],
        },
    }
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASE_URL = _resolve_database_url()
_assert_local_test_database(DATABASE_URL)
DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        engine="tenant_schemas.postgresql_backend",
        # Keep 0 for the ASGI REST service: Django-ASGI runs each request in its
        # own thread (asgiref ThreadSensitiveContext), so a persistent connection
        # is never reused by a later request -- it only defers the close to GC.
        conn_max_age=config("CONN_MAX_AGE", default=0, cast=int),
        conn_health_checks=True,
    ),
}

# HTTP concurrency ceiling (ASGI). Each in-flight request holds one OS thread
# and one Postgres connection (CONN_MAX_AGE=0, thread-per-request). Default 60
# sits above projected peak at 1500 DAU (~10-30 concurrent) while leaving
# headroom on typical Railway max_connections for broker + celery. Set to 0
# to disable. /api/v1/health is exempt so a probe cannot consume a slot.
ASGI_MAX_CONCURRENT_REQUESTS = config(
    "ASGI_MAX_CONCURRENT_REQUESTS", default=60, cast=int
)
ASGI_CONCURRENCY_QUEUE_TIMEOUT = config(
    "ASGI_CONCURRENCY_QUEUE_TIMEOUT", default=5.0, cast=float
)
ASGI_CONCURRENCY_MAX_QUEUE = config(
    "ASGI_CONCURRENCY_MAX_QUEUE", default=120, cast=int
)
ASGI_CONCURRENCY_EXEMPT_PREFIXES = tuple(
    p.strip()
    for p in config(
        "ASGI_CONCURRENCY_EXEMPT_PREFIXES",
        default="/api/v1/health",
    ).split(",")
    if p.strip()
)

# Use the main database for tests (local Docker) instead of cloning test_*.
if config("SCHEDJUICE_TEST_USE_MAIN_DB", default=False, cast=bool):
    DATABASES["default"]["TEST"] = {"NAME": DATABASES["default"]["NAME"]}
elif os.environ.get("SCHEDJUICE_TEST_DB_NAME"):
    DATABASES["default"]["TEST"] = {"NAME": os.environ["SCHEDJUICE_TEST_DB_NAME"]}

DATABASE_ROUTERS = ("tenant_schemas.routers.TenantSyncRouter",)

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cache: LocMem locally (per-process); Redis in production (shared across workers).
# Override with DJANGO_CACHE_USE_REDIS=true|false (default: use Redis when DEBUG is False).
_USE_REDIS_CACHE = config("DJANGO_CACHE_USE_REDIS", default=not DEBUG, cast=bool)
if _USE_REDIS_CACHE:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": _redis_url_with_db(1),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "SOCKET_CONNECT_TIMEOUT": 1,
                "SOCKET_TIMEOUT": 1,
                "RETRY_ON_TIMEOUT": True,
                "IGNORE_EXCEPTIONS": True,
                "CONNECTION_POOL_KWARGS": {
                    "socket_connect_timeout": 1,
                    "socket_timeout": 1,
                    "retry_on_timeout": True,
                },
            },
            "KEY_PREFIX": "schedjuice",
        }
    }
    DJANGO_REDIS_IGNORE_EXCEPTIONS = True
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "schedjuice-default",
        }
    }

# Tenant resolution (middleware): cache TTL for domain/schema -> org pk mapping
TENANT_RESOLUTION_CACHE_TIMEOUT = config(
    "TENANT_RESOLUTION_CACHE_TIMEOUT", default=60, cast=int
)

# Course chat HTTP list (GET …/courses/<id>/chat/messages): Redis cache TTL (seconds)
COURSE_CHAT_LIST_CACHE_TIMEOUT = config(
    "COURSE_CHAT_LIST_CACHE_TIMEOUT", default=120, cast=int
)

# Zoom integration (admin-managed OAuth app + per-org connected ZoomAccount tokens)
ZOOM_TOKEN_ENCRYPTION_KEY = config("ZOOM_TOKEN_ENCRYPTION_KEY", default="")
TELEGRAM_TOKEN_ENCRYPTION_KEY = config("TELEGRAM_TOKEN_ENCRYPTION_KEY", default="")
TELEGRAM_WEBHOOK_BASE_URL = config("TELEGRAM_WEBHOOK_BASE_URL", default="")
ZOOM_OAUTH_CLIENT_ID = config("ZOOM_OAUTH_CLIENT_ID", default="")
ZOOM_OAUTH_CLIENT_SECRET = config("ZOOM_OAUTH_CLIENT_SECRET", default="")
ZOOM_OAUTH_REDIRECT_URL = config("ZOOM_OAUTH_REDIRECT_URL", default="")
ZOOM_OAUTH_STATE_TTL_SECONDS = config(
    "ZOOM_OAUTH_STATE_TTL_SECONDS", default=600, cast=int
)
FRONTEND_BASE_URL = config("FRONTEND_BASE_URL", default="")

# Microsoft delegated OAuth (per-teacher + org service account MSAL caches)
MS_TOKEN_ENCRYPTION_KEY = config("MS_TOKEN_ENCRYPTION_KEY", default="")
MS_OAUTH_REDIRECT_URL = config("MS_OAUTH_REDIRECT_URL", default="")
MS_OAUTH_STATE_TTL_SECONDS = config(
    "MS_OAUTH_STATE_TTL_SECONDS", default=600, cast=int
)

# Google Sign-In (platform-wide OAuth web client — authorization-code flow)
GOOGLE_OAUTH_CLIENT_ID = config("GOOGLE_OAUTH_CLIENT_ID", default="")
GOOGLE_OAUTH_CLIENT_SECRET = config("GOOGLE_OAUTH_CLIENT_SECRET", default="")
GOOGLE_OAUTH_REDIRECT_URL = config("GOOGLE_OAUTH_REDIRECT_URL", default="")
GOOGLE_OAUTH_STATE_TTL_SECONDS = config(
    "GOOGLE_OAUTH_STATE_TTL_SECONDS", default=600, cast=int
)
GOOGLE_TOKEN_ENCRYPTION_KEY = config("GOOGLE_TOKEN_ENCRYPTION_KEY", default="")
GOOGLE_CALENDAR_WEBHOOK_BASE_URL = config("GOOGLE_CALENDAR_WEBHOOK_BASE_URL", default="")

# CORS
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = (
    *default_headers,
    "content-range",
    "x-tenant",
    "tenant",
    "HTTP_X_TENANT_URL",
    "X-Tenant",
)

# Authentication
AUTH_USER_MODEL = "app_auth.User"
TENANT_MODEL = "app_organization.Organization"

# RBAC enforcement mode (Plan 1 ships log_only: record would-be denials, never block).
RBAC_ENFORCE = config("RBAC_ENFORCE", default="log_only")  # log_only | enforce

# Django REST framework (envelope renderer + consistent exception shape)
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "utilitas.exception_handler.custom_handler",
    "DEFAULT_RENDERER_CLASSES": [
        "utilitas.renderer.CustomRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "organization_public": "120/minute",
    },
}

# JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=90),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
    "SIGNING_KEY": config("JWT"),
    "USER_ID_FIELD": "email",
}

# Django Debug Toolbar
INTERNAL_IPS = [
    "127.0.0.1",
]

# File storage
# https://github.com/bernardopires/django-tenant-schemas/issues/565
# https://www.digitalocean.com/community/questions/botocore-exceptions-clienterror-an-error-occurred-invalidargument-when-calling-the-putobject-operation-unknown


def _normalize_s3_host(value: str) -> str:
    return value.removeprefix("https://").removeprefix("http://").rstrip("/")


def _do_public_url_bucket_prefix(cdn_host: str | None, bucket_name: str) -> str:
    """
    When one CDN hostname serves multiple Spaces buckets, public URLs need the
    bucket name in the path (path-style), e.g.
    https://schedjuice-dev.sgp1.cdn.../schedjuice-prod/media-prod/public/...
    """
    if not cdn_host:
        return ""
    if cdn_host.startswith(f"{bucket_name}."):
        return ""
    return f"{bucket_name}/"


def _resolve_do_spaces_storage(
    *,
    endpoint: str,
    legacy_custom_domain: str,
    cdn_domain: str,
    static_location: str,
    bucket_name: str,
) -> dict[str, str | None]:
    """
    Split DO Spaces origin (boto uploads/presigning) from CDN hostname (public URLs).

    S3_ENDPOINT — regional or bucket origin URL for API calls.
    S3_CDN_DOMAIN — optional CDN edge hostname for public reads.
    S3_CUSTOM_DOMAIN — legacy fallback for endpoint when S3_ENDPOINT is unset.
    """
    endpoint_raw = (endpoint or "").strip() or (legacy_custom_domain or "").strip()
    if not endpoint_raw:
        raise ImproperlyConfigured(
            "STORAGE_BACKEND=do requires S3_ENDPOINT or S3_CUSTOM_DOMAIN"
        )

    endpoint_host = _normalize_s3_host(endpoint_raw)
    if endpoint_raw.startswith("http://") or endpoint_raw.startswith("https://"):
        endpoint_url = endpoint_raw.rstrip("/")
    else:
        endpoint_url = f"https://{endpoint_host}"

    cdn_host = (
        _normalize_s3_host(cdn_domain) if (cdn_domain or "").strip() else None
    )
    if cdn_host:
        public_host = cdn_host
    elif (legacy_custom_domain or "").strip():
        public_host = _normalize_s3_host(legacy_custom_domain)
    else:
        public_host = f"{bucket_name}.sgp1.digitaloceanspaces.com"

    bucket_prefix = _do_public_url_bucket_prefix(cdn_host, bucket_name)

    if (legacy_custom_domain or "").strip():
        bucket_origin_url = f"https://{_normalize_s3_host(legacy_custom_domain)}"
    else:
        bucket_origin_url = f"https://{bucket_name}.sgp1.digitaloceanspaces.com"

    return {
        "AWS_S3_ENDPOINT_URL": endpoint_url,
        "AWS_S3_CUSTOM_DOMAIN": cdn_host,
        "AWS_S3_BUCKET_ORIGIN_URL": bucket_origin_url,
        "STATIC_URL": f"https://{public_host}/{bucket_prefix}{static_location}/",
    }


# 100 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600

STORAGE_BACKEND = config("STORAGE_BACKEND")
AWS_STATIC_LOCATION = config("S3_STATIC_LOCATION")
AWS_ACCESS_KEY_ID = config("S3_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("S3_SECRET")
AWS_STORAGE_BUCKET_NAME = config("S3_BUCKET_NAME")

if STORAGE_BACKEND == "aws":
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_STATIC_LOCATION}/"
    AWS_S3_REGION_NAME = config("S3_REGION", default="us-east-1")

elif STORAGE_BACKEND == "do":
    _do_storage = _resolve_do_spaces_storage(
        endpoint=config("S3_ENDPOINT", default=""),
        legacy_custom_domain=config("S3_CUSTOM_DOMAIN", default=""),
        cdn_domain=config("S3_CDN_DOMAIN", default=""),
        static_location=AWS_STATIC_LOCATION,
        bucket_name=AWS_STORAGE_BUCKET_NAME,
    )
    AWS_S3_ENDPOINT_URL = _do_storage["AWS_S3_ENDPOINT_URL"]
    AWS_S3_CUSTOM_DOMAIN = _do_storage["AWS_S3_CUSTOM_DOMAIN"]
    AWS_S3_BUCKET_ORIGIN_URL = _do_storage["AWS_S3_BUCKET_ORIGIN_URL"]
    STATIC_URL = _do_storage["STATIC_URL"]
    AWS_S3_REGION_NAME = "sgp1"
    AWS_S3_PRIVATE_PRESIGN_ADDRESSING_STYLE = "virtual"

AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}
STATICFILES_STORAGE = "schedjuice_backend.storages.StaticStorage"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, f"static/{AWS_STATIC_LOCATION}"),
]

AWS_MEDIA_LOCATION = config("S3_MEDIA_LOCATION")
MEDIA_ROOT = os.path.join(os.getcwd(), AWS_MEDIA_LOCATION)
MEDIA_URL = "/media/"

AWS_PUBLIC_MEDIA_LOCATION = f"{AWS_MEDIA_LOCATION}/public"
DEFAULT_FILE_STORAGE = "schedjuice_backend.storages.PublicMediaStorage"

AWS_PRIVATE_MEDIA_LOCATION = f"{AWS_MEDIA_LOCATION}/private"
MEETING_RECORDINGS_SUBFOLDER = config(
    "MEETING_RECORDINGS_SUBFOLDER", default="meeting_recordings"
)
# Optional Discord incoming webhook for ops alerts (cron failures, gap digest).
RESEND_API_KEY = config("RESEND_API_KEY", default="")
RESEND_FROM_EMAIL = config("RESEND_FROM_EMAIL", default="noreply@mail.schedjuice.com")
RESEND_FROM_NAME = config("RESEND_FROM_NAME", default="Schedjuice")
RESEND_REPLY_TO = config("RESEND_REPLY_TO", default="")
RESEND_TIMEOUT = config("RESEND_TIMEOUT", default=15, cast=int)
DISCORD_WEBHOOK_URL = config("DISCORD_WEBHOOK_URL", default="")
# Mobile EAS build/submit → Discord (separate channel from ops alerts).
EAS_DISCORD_WEBHOOK_URL = config("EAS_DISCORD_WEBHOOK_URL", default="")
EAS_WEBHOOK_SECRET = config("EAS_WEBHOOK_SECRET", default="")
# Optional Expo access token for enriching submit Discord alerts (build profile lookup).
EXPO_TOKEN = config("EXPO_TOKEN", default="")
GITHUB_DOCS_VIDEO_TOKEN = config("GITHUB_DOCS_VIDEO_TOKEN", default="")
GITHUB_DOCS_VIDEO_REPO = config("GITHUB_DOCS_VIDEO_REPO", default="")
GITHUB_DOCS_VIDEO_RELEASE_TAG = config("GITHUB_DOCS_VIDEO_RELEASE_TAG", default="videos")
PLATFORM_SECRETS_ENCRYPTION_KEY = config("PLATFORM_SECRETS_ENCRYPTION_KEY", default="")
OCR_API_KEY = config("OCR_API_KEY")
OCR_ENDPOINTS = config(
    "OCR_ENDPOINTS",
    default="https://apipro1.ocr.space/parse/image,https://apipro2.ocr.space/parse/image",
    cast=Csv(),
)
OCR_TIMEOUT = config("OCR_TIMEOUT", default=30, cast=int)
OCR_MONTHLY_QUOTA = config("OCR_MONTHLY_QUOTA", default=None, cast=lambda v: int(v) if v else None)
PRIVATE_FILE_STORAGE = "schedjuice_backend.storages.PrivateMediaStorage"
AWS_QUERYSTRING_EXPIRE = 24 * 3600  # 24 hours
RECORDING_SHARE_JWT_EXPIRES = datetime.timedelta(days=10)
RECORDING_PRESIGNED_EXPIRES_SECONDS = config(
    "RECORDING_PRESIGNED_EXPIRES_SECONDS",
    default=10 * 24 * 60 * 60,
    cast=int,
)
# AWS SigV4 presigned URLs are capped at 7 days.
if STORAGE_BACKEND == "aws":
    RECORDING_PRESIGNED_EXPIRES_SECONDS = min(
        RECORDING_PRESIGNED_EXPIRES_SECONDS, 7 * 24 * 60 * 60
    )
# Celery (required for django-expo-notifications)
# Uses same Redis as django-q2
CELERY_BROKER_URL = _redis_url_with_db(2)
CELERY_RESULT_BACKEND = _redis_url_with_db(3)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100
# Max Message/Ticket PKs per Celery task (bounds worker RSS during Expo fan-out).
EXPO_PUSH_CELERY_CHUNK_SIZE = 200
# Max recipient user IDs per push fan-out Celery task (bounds device query + bulk_create).
PUSH_FANOUT_CELERY_CHUNK_SIZE = 300

# django-expo-notifications settings (optional)
# EXPO_NOTIFICATIONS_TOKEN = None  # Set for Enhanced Security
# EXPO_NOTIFICATIONS_RECEIPT_CHECK_DELAY = timedelta(minutes=30)
# Android: must match the channel id registered in the app (e.g. expo-notifications setNotificationChannelAsync).
EXPO_NOTIFICATIONS_DEFAULT_ANDROID_CHANNEL_ID = "default"

# scheduler (django-q2)
Q_CLUSTER = {
    "workers": config("Q_CLUSTER_WORKERS", default=5, cast=int),
    "recycle": 500,
    "timeout": config("Q_CLUSTER_TIMEOUT", default=900, cast=int),
    "retry": config("Q_CLUSTER_RETRY", default=1200, cast=int),
    "compress": True,
    "save_limit": 250,
    "queue_limit": 500,
    "ack_failures": True,
    "cpu_affinity": 1,
    "label": "Django Q2",
    "redis": _redis_url_with_db(4),
}

# Chunked uploads
from schedjuice_backend.storages import PrivateMediaStorage

DRF_CHUNKED_UPLOAD_STORAGE_CLASS = PrivateMediaStorage
DRF_CHUNKED_UPLOAD_USER_RESTRICTED = False

# Academic Hub course search tuning.
COURSE_SEARCH_FUZZY_ENABLED = config(
    "COURSE_SEARCH_FUZZY_ENABLED", default=True, cast=bool
)
COURSE_SEARCH_TRIGRAM_THRESHOLD = config(
    "COURSE_SEARCH_TRIGRAM_THRESHOLD", default=0.25, cast=float
)
COURSE_SEARCH_FALLBACK_MIN_RESULTS = config(
    "COURSE_SEARCH_FALLBACK_MIN_RESULTS", default=1, cast=int
)

CATEGORY_SEARCH_TRIGRAM_THRESHOLD = config(
    "CATEGORY_SEARCH_TRIGRAM_THRESHOLD", default=0.25, cast=float
)
CATEGORY_SEARCH_FALLBACK_MIN_RESULTS = config(
    "CATEGORY_SEARCH_FALLBACK_MIN_RESULTS", default=1, cast=int
)

# User Hub fuzzy search tuning.
USER_SEARCH_FUZZY_ENABLED = config("USER_SEARCH_FUZZY_ENABLED", default=True, cast=bool)
USER_SEARCH_TRIGRAM_THRESHOLD = config(
    "USER_SEARCH_TRIGRAM_THRESHOLD", default=0.25, cast=float
)
USER_SEARCH_FALLBACK_MIN_RESULTS = config(
    "USER_SEARCH_FALLBACK_MIN_RESULTS", default=1, cast=int
)

# Import Wizard course-matching tuning.
IMPORT_COURSE_MATCH_HIGH = config("IMPORT_COURSE_MATCH_HIGH", default=90.0, cast=float)
IMPORT_COURSE_MATCH_LOW = config("IMPORT_COURSE_MATCH_LOW", default=55.0, cast=float)
IMPORT_COURSE_MATCH_MARGIN = config(
    "IMPORT_COURSE_MATCH_MARGIN", default=8.0, cast=float
)
IMPORT_COURSE_RECENCY_YEARS = config("IMPORT_COURSE_RECENCY_YEARS", default=2, cast=int)
IMPORT_COURSE_CANDIDATE_LIMIT = config(
    "IMPORT_COURSE_CANDIDATE_LIMIT", default=6, cast=int
)

# Import Wizard user-matching tuning (stricter than course matching).
IMPORT_USER_MATCH_FUZZY_MIN = config(
    "IMPORT_USER_MATCH_FUZZY_MIN", default=88.0, cast=float
)
IMPORT_USER_MATCH_CANDIDATE_LIMIT = config(
    "IMPORT_USER_MATCH_CANDIDATE_LIMIT", default=5, cast=int
)
IMPORT_USER_PHONE_TAIL_DIGITS = config(
    "IMPORT_USER_PHONE_TAIL_DIGITS", default=7, cast=int
)

IMPORT_PARSE_MAX_ROWS = config("IMPORT_PARSE_MAX_ROWS", default=5000, cast=int)
IMPORT_PARSE_MAX_BYTES = config(
    "IMPORT_PARSE_MAX_BYTES", default=10 * 1024 * 1024, cast=int
)

# Web Push / VAPID settings
WEB_PUSH_VAPID_PUBLIC_KEY = config("WEB_PUSH_VAPID_PUBLIC_KEY", default="", cast=str)
WEB_PUSH_VAPID_SUBJECT = config("WEB_PUSH_VAPID_SUBJECT", default="", cast=str)


def _load_web_push_vapid_private_key() -> str:
    raw = config("WEB_PUSH_VAPID_PRIVATE_KEY", default="", cast=str).strip().strip('"')
    default_pem = BASE_DIR / "private_key.pem"

    if not raw:
        return str(default_pem) if default_pem.is_file() else ""

    pem_path = Path(raw)
    if not pem_path.is_file() and not pem_path.is_absolute():
        pem_path = BASE_DIR / raw
    if pem_path.is_file():
        return str(pem_path.resolve())

    if "BEGIN PRIVATE KEY" in raw and "END PRIVATE KEY" in raw:
        return raw

    if default_pem.is_file():
        return str(default_pem.resolve())

    return raw


WEB_PUSH_VAPID_PRIVATE_KEY = _load_web_push_vapid_private_key()

if SILK_ENABLED:
    # Silk uses @login_required; default LOGIN_URL is /accounts/login/ which this project does not expose.
    LOGIN_URL = "/admin/login/"
    SILKY_AUTHENTICATION = True
    SILKY_AUTHORISATION = True
    SILKY_PYTHON_PROFILER = False
    SILKY_INTERCEPT_PERCENT = 100
    SILKY_MAX_RECORDED_REQUESTS = 10_000
    # JSONField + Silk EXPLAIN monkeypatch runs in app_chat.apps.AppChatConfig.ready (not here:
    # importing silk.sql during settings load triggers AppRegistryNotReady).

# OpenAI / AI tool-calling
OPENAI_API_KEY = config("OPENAI_API_KEY", default="")
AI_DEFAULT_MODEL = config("AI_DEFAULT_MODEL", default="gpt-5.6-luna")
AI_MAX_TOOL_ITERATIONS = config("AI_MAX_TOOL_ITERATIONS", default=5, cast=int)
AI_BILLING_MARKUP = config("AI_BILLING_MARKUP", default=1.0, cast=float)
AI_DEFAULT_MONTHLY_USD_LIMIT = config("AI_DEFAULT_MONTHLY_USD_LIMIT", default=50.0, cast=float)
AI_DEFAULT_USER_MONTHLY_USD_LIMIT = config(
    "AI_DEFAULT_USER_MONTHLY_USD_LIMIT", default=1.0, cast=float
)
AI_DEFAULT_MONTHLY_TOKEN_LIMIT = config("AI_DEFAULT_MONTHLY_TOKEN_LIMIT", default=None)
AI_DEFAULT_HARD_ENFORCE = config("AI_DEFAULT_HARD_ENFORCE", default=False, cast=bool)
AI_DEFAULT_ALERT_THRESHOLDS = config(
    "AI_DEFAULT_ALERT_THRESHOLDS",
    default="0.5,0.8,1.0",
    cast=lambda v: [float(x.strip()) for x in v.split(",") if x.strip()],
)
AI_RATE_LIMIT_PER_USER = config("AI_RATE_LIMIT_PER_USER", default=30, cast=int)
AI_RATE_LIMIT_WINDOW_SECONDS = config("AI_RATE_LIMIT_WINDOW_SECONDS", default=3600, cast=int)
AI_GUARDRAIL_CLASSIFIER_MODEL = config(
    "AI_GUARDRAIL_CLASSIFIER_MODEL", default="gpt-5.6-luna"
)
AI_CAPABILITY_GAP_JUDGE_MODEL = config(
    "AI_CAPABILITY_GAP_JUDGE_MODEL", default="gpt-5.6-luna"
)
AI_GUARDRAIL_FAIL_OPEN = config("AI_GUARDRAIL_FAIL_OPEN", default=True, cast=bool)
AI_PROMPT_CACHE_ENABLED = config("AI_PROMPT_CACHE_ENABLED", default=True, cast=bool)
AI_REASONING_EFFORT = config("AI_REASONING_EFFORT", default="high")
AI_GUARDRAIL_REASONING_EFFORT = config(
    "AI_GUARDRAIL_REASONING_EFFORT", default="low"
)
AI_CAPABILITY_GAP_REASONING_EFFORT = config(
    "AI_CAPABILITY_GAP_REASONING_EFFORT", default="medium"
)
AI_TOOL_RESULT_MAX_ITEMS = config("AI_TOOL_RESULT_MAX_ITEMS", default=50, cast=int)
AI_TOOL_RESULT_MAX_CHARS = config("AI_TOOL_RESULT_MAX_CHARS", default=8000, cast=int)
