from django.urls import path

from app_microsoft import oauth_views, views

urlpatterns = [
    path(
        "microsoft/oauth/start/personal",
        oauth_views.MicrosoftOAuthPersonalStartView.as_view(),
        name="microsoft-oauth-personal-start",
    ),
    path(
        "microsoft/oauth/personal/reconnect",
        oauth_views.MicrosoftOAuthPersonalReconnectView.as_view(),
        name="microsoft-oauth-personal-reconnect",
    ),
    path(
        "microsoft/oauth/personal/disconnect",
        oauth_views.MicrosoftOAuthPersonalDisconnectView.as_view(),
        name="microsoft-oauth-personal-disconnect",
    ),
    path(
        "microsoft/oauth/personal/status",
        oauth_views.MicrosoftOAuthPersonalStatusView.as_view(),
        name="microsoft-oauth-personal-status",
    ),
    path(
        "microsoft/oauth/start/service-account",
        oauth_views.MicrosoftOAuthServiceAccountStartView.as_view(),
        name="microsoft-oauth-service-start",
    ),
    path(
        "microsoft/oauth/service-account/reconnect",
        oauth_views.MicrosoftOAuthServiceAccountReconnectView.as_view(),
        name="microsoft-oauth-service-reconnect",
    ),
    path(
        "microsoft/oauth/service-account/disconnect",
        oauth_views.MicrosoftOAuthServiceAccountDisconnectView.as_view(),
        name="microsoft-oauth-service-disconnect",
    ),
    path(
        "microsoft/oauth/service-account/status",
        oauth_views.MicrosoftOAuthServiceAccountStatusView.as_view(),
        name="microsoft-oauth-service-status",
    ),
    path(
        "microsoft/oauth/callback",
        oauth_views.MicrosoftOAuthCallbackView.as_view(),
        name="microsoft-oauth-callback",
    ),
    path(
        "microsoft/repair/dry-run",
        views.MicrosoftRepairDryRunView.as_view(),
        name="microsoft-repair-dry-run",
    ),
    path(
        "microsoft/repair/jobs",
        views.MicrosoftRepairJobListCreateView.as_view(),
        name="microsoft-repair-jobs",
    ),
    path(
        "microsoft/repair/jobs/<int:job_id>",
        views.MicrosoftRepairJobDetailView.as_view(),
        name="microsoft-repair-job-detail",
    ),
    path(
        "microsoft/health",
        views.MicrosoftHealthView.as_view(),
        name="microsoft-health",
    ),
    path(
        "microsoft/password-reset/preview",
        views.MicrosoftPasswordResetPreviewView.as_view(),
        name="microsoft-password-reset-preview",
    ),
    path(
        "microsoft/password-reset/commit",
        views.MicrosoftPasswordResetCommitView.as_view(),
        name="microsoft-password-reset-commit",
    ),
    path(
        "microsoft/password-reset/jobs",
        views.MicrosoftPasswordResetJobCreateView.as_view(),
        name="microsoft-password-reset-job-create",
    ),
    path(
        "microsoft/password-reset/jobs/<int:job_id>",
        views.MicrosoftPasswordResetJobDetailView.as_view(),
        name="microsoft-password-reset-job-detail",
    ),
    path(
        "microsoft/password-reset/jobs/<int:job_id>/cancel",
        views.MicrosoftPasswordResetJobCancelView.as_view(),
        name="microsoft-password-reset-job-cancel",
    ),
]
