from django.urls import path

from app_finance import views

urlpatterns = [
    path(
        "verify-screenshots",
        views.VerifyScreenshotsView.as_view(),
        name="verify-screenshots",
    ),
    path(
        "receiver-side-screenshots",
        views.ReceiverSideScreenshotListView.as_view(),
        name="receiver-side-screenshots-list",
    ),
    path(
        "receiver-side-screenshots/<int:obj_id>",
        views.ReceiverSideScreenshotDetailsView.as_view(),
        name="receiver-side-screenshots-details",
    ),
    path(
        "receiver-side-screenshots/search",
        views.ReceiverSideScreenshotSearchView.as_view(),
        name="receiver-side-screenshots-search",
    ),
    path(
        "user-payments/<int:obj_id>/adjustments",
        views.PaymentAdjustmentListCreateView.as_view(),
        name="user-payment-adjustments",
    ),
    path(
        "payment-adjustments/<int:obj_id>",
        views.PaymentAdjustmentDetailsView.as_view(),
        name="payment-adjustment-details",
    ),
    path(
        "user-payments/<int:obj_id>/retry-extraction",
        views.RetryUserPaymentExtractionView.as_view(),
        name="user-payment-retry-extraction",
    ),
    path(
        "user-payments/<int:obj_id>",
        views.UserPaymentDetailsView.as_view(),
        name="user-payment-details",
    ),
    path(
        "user-payment-groups/<int:obj_id>",
        views.UserPaymentGroupDetailsView.as_view(),
        name="user-payment-group-details",
    ),
    path(
        "user-payments/search",
        views.UserPaymentSearchView.as_view(),
        name="user-payment-search",
    ),
    path(
        "user-payments/unpaid",
        views.UnpaidUserPaymentView.as_view(),
        name="user-payments-unpaid",
    ),
    path(
        "user-payments/unpaid-course-summary",
        views.UnpaidCourseSummaryView.as_view(),
        name="user-payments-unpaid-course-summary",
    ),
    path(
        "user-payments/admin-report",
        views.UserPaymentAdminReportView.as_view(),
        name="user-payments-admin-report",
    ),
    path(
        "user-payments/coverage-review",
        views.StudentPaymentsCoverageReviewView.as_view(),
        name="user-payments-coverage-review",
    ),
    path("make-payment", views.StudentMakePaymentView.as_view(), name="make-payment"),
    path(
        "user-payments/ensure-enrollments",
        views.EnsurePaymentEnrollmentsView.as_view(),
        name="user-payments-ensure-enrollments",
    ),
    path(
        "scan-transaction-screenshots",
        views.AdminUploadScreenshotView.as_view(),
        name="scan-receiver-screenshots",
    ),
    path(
        "ocr-payment-screenshot",
        views.OcrPaymentScreenshotView.as_view(),
        name="ocr-payment-screenshot",
    ),
    path("payment-plans", views.PaymentPlanListView.as_view(), name="payment-plans"),
    path(
        "payment-plans/<int:obj_id>",
        views.PaymentPlanDetailsView.as_view(),
        name="payment-plan-details",
    ),
    path(
        "payment-plans/search",
        views.PaymentPlanSearchView.as_view(),
        name="payment-plan-search",
    ),
    path("discounts", views.DiscountListView.as_view(), name="discounts"),
    path(
        "discounts/<int:obj_id>",
        views.DiscountDetailsView.as_view(),
        name="discount-details",
    ),
    path(
        "discounts/search", views.DiscountSearchView.as_view(), name="discount-search"
    ),
    path(
        "user-courses/<int:user_course_id>/eligible-discounts",
        views.EligibleDiscountsView.as_view(),
        name="eligible-discounts",
    ),
    path(
        "user-courses/<int:user_course_id>/discount",
        views.EnrollmentDiscountView.as_view(),
        name="user-course-discount",
    ),
    path(
        "user-courses/<int:user_course_id>/discount/<int:enrollment_discount_id>",
        views.EnrollmentDiscountDetailView.as_view(),
        name="user-course-discount-detail",
    ),
    path(
        "user-courses/<int:user_course_id>/discount-preview",
        views.EnrollmentDiscountPreviewView.as_view(),
        name="user-course-discount-preview",
    ),
    path(
        "payment-methods", views.PaymentMethodListView.as_view(), name="payment-methods"
    ),
    path(
        "payment-methods/<int:obj_id>",
        views.PaymentMethodDetailsView.as_view(),
        name="payment-method-details",
    ),
    path(
        "payment-methods/search",
        views.PaymentMethodSearchView.as_view(),
        name="payment-method-search",
    ),
    path("payment-infos", views.PaymentInfoListView.as_view(), name="payment-infos"),
    path(
        "payment-infos/<int:obj_id>",
        views.PaymentInfoDetailsView.as_view(),
        name="payment-info-details",
    ),
    path(
        "payment-infos/search",
        views.PaymentInfoSearchView.as_view(),
        name="payment-info-search",
    ),
    path("staff-payments", views.StaffPaymentListView.as_view(), name="staff-payments"),
    path(
        "staff-payments/<int:obj_id>",
        views.StaffPaymentDetailsView.as_view(),
        name="staff-payment-details",
    ),
    path(
        "staff-payments/<int:obj_id>/confirm",
        views.StaffPaymentConfirmView.as_view(),
        name="staff-payment-confirm",
    ),
    path(
        "staff-payments/search",
        views.StaffPaymentSearchView.as_view(),
        name="staff-payment-search",
    ),
    path(
        "student-payment-aggregate",
        views.StudentPaymentMonthlyAggregateView.as_view(),
        name="student-payment-aggregate",
    ),
    path("billing", views.BillingMonthlyView.as_view(), name="billing"),
    path(
        "finance/homepage",
        views.FinanceHomepageView.as_view(),
        name="finance-homepage",
    ),
]
